### PR TITLE
Save encryption configuration

### LINKED ISSUE #1665: How to set new encryption in JSON config?
Could somebody give an example how to use the new encryption syntax within a preconfigured JSON config like https://github.com/archlinux/archinstall/blob/master/examples/disk_layouts-sample.json?

Is this even possible?

### PR DESCRIPTION
**Pull request by svartkanin**
Fixes #1665 

The encryption configuration is stored as:
*  `user_configuration.json`: Will store everything EXCEPT the password 
```
    "disk_encryption": {
        "encryption_type": "partition",
        "partitions": {
            "/dev/sdb": [
                {
                    "encrypted": false,
                    "filesystem": {
                        "format": "ext4",
                        "mount_options": []
                    },
                    "mountpoint": "/",
                    "size": "20GiB",
                    "start": "513MiB",
                    "type": "primary",
                    "wipe": true
                }
            ]
        }
    },
 ```
 *  `user_credentials.json`: Will store ONLY the encryption password
```
{
    "encryption_password": "asdf"
}
```

The reason for this split is that when users report bugs, they can safely provide the user configuration file with the encryption configuration which will help in narrowing down issues.

### CODE REVIEW

**Comment by svartkanin** [comment]
There's still a bug in there, will fix it tomorrow

**Comment by svartkanin** [comment]
Alrighty this should be good now

**Comment by svartkanin** [comment]
I'm a bit confused about the flake8 errors, they are not related to any of my changes?

**Comment by rgrewe** [comment]
I tested your last changes. Works for me. Anything missing for merging?

**Comment by svartkanin** [comment]
All good then

**Comment by Torxed** [comment]
Awesome, I'll verify and merge later today hopefully!

**Comment by Torxed** [comment]
Merged the PEP8 fixes from the other PR to give that author some credit

**Comment by rgrewe** [comment]
Hey ho, anything more missing here? Would be nice if this could be merged.
Also, when will this get released?

**Comment by Torxed** [comment]
There's some slight issues with the JSON decoder:

screenshot

But I suspect it's a different PR triggering it as it's the `Subvolume()` missing a `json()` function.

**Comment by Torxed** [comment]
I'll try to merge this in the morning.
I still can't properly test this PR until I sort out some slightly unrelated issues that keep popping up one by one:
screenshot

*(I want to run through a couple of successful installs before merging)*

**Comment by svartkanin** [comment]
If it helps, I've also fixed this in the pyparted PR. So if there's a plan to merge that in soonish we may just be able to focus on that?

**Comment by Torxed** [comment]
> If it helps, I've also fixed this in the pyparted PR. So if there's a plan to merge that in soonish we may just be able to focus on that?

The plan was to release v2.5.4 today as the last minor release as I think most issues not related to disk operations is patched now. And then drop v2.6 which introduces dependencies and pyparted.

**Comment by Torxed** [comment]
PR looks good overall, but I think we're missing the reading in of a config:
screenshot

**Comment by svartkanin** [comment]
Can you share tge config you're reading in, mine worked (TM)

**Comment by Torxed** [comment]
just about to head to bed but i'll fix a conf + video in the morning :)

**Comment by Torxed** [comment]
How I build and test with an ISO:

`python github/Torxed/Scripts/python/archtest.py --repo https://github.com/svartkanin/archinstall.git --branch save-enc-config --bridge-mac 'fe:00:00:00:00:00' --bridge 'internetbr' --internet enp0s31f6 --new-drives --rebuild`

Here's a video:
 * https://youtu.be/g9y1FZ07EHw

Here's the conf used in the video:
```json
{
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio": null,
    "bootloader": "systemd-bootctl",
    "config_version": "2.5.3",
    "debug": false,
    "disk_encryption": {
        "encryption_type": "partition",
        "partitions": {
            "/dev/sda": [
                {
                    "btrfs": {
                        "subvolumes": [
                            {
                                "compress": false,
                                "mountpoint": "/",
                                "name": "@",
                                "nodatacow": false
                            },
                            {
                                "compress": false,
                                "mountpoint": "/home",
                                "name": "@home",
                                "nodatacow": false
                            },
                            {
                                "compress": false,
                                "mountpoint": "/var/log",
                                "name": "@log",
                                "nodatacow": false
                            },
                            {
                                "compress": false,
                                "mountpoint": "/var/cache/pacman/pkg",
                                "name": "@pkg",
                                "nodatacow": false
                            },
                            {
                                "compress": false,
                                "mountpoint": "/.snapshots",
                                "name": "@.snapshots",
                                "nodatacow": false
                            }
                        ]
                    },
                    "encrypted": false,
                    "filesystem": {
                        "format": "btrfs",
                        "mount_options": [
                            "compress=zstd"
                        ]
                    },
                    "mountpoint": null,
                    "size": "100%",
                    "start": "513MiB",
                    "type": "primary",
                    "wipe": true
                }
            ]
        }
    },
    "harddrives": [
        "/dev/sda"
    ],
    "hostname": "archlinux",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "sv-latin1",
    "mirror-region": {
        "Sweden": {
            "http://ftp.acc.umu.se/mirror/archlinux/$repo/os/$arch": true,
            "http://ftp.lysator.liu.se/pub/archlinux/$repo/os/$arch": true,
            "http://ftp.myrveln.se/pub/linux/archlinux/$repo/os/$arch": true,
            "http://ftpmirror.infania.net/mirror/archlinux/$repo/os/$arch": true,
            "https://ftp.acc.umu.se/mirror/archlinux/$repo/os/$arch": true,
            "https://ftp.ludd.ltu.se/mirrors/archlinux/$repo/os/$arch": true,
            "https://ftp.lysator.liu.se/pub/archlinux/$repo/os/$arch": true,
            "https://ftp.myrveln.se/pub/linux/archlinux/$repo/os/$arch": true,
            "https://mirror.osbeck.com/archlinux/$repo/os/$arch": true
        }
    },
    "nic": {},
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [],
    "parallel downloads": 0,
    "profile": null,
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": true,
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "UTC",
    "version": "2.5.3"
}
```

Creds
```json
{
    "!users": [
        {
            "sudo": true,
            "username": "anton"
        }
    ],
    "encryption_password": "test"
}
```

Disk layout:
```json
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "btrfs": {
                    "subvolumes": [
                        {
                            "compress": false,
                            "mountpoint": "/",
                            "name": "@",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/home",
                            "name": "@home",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/var/log",
                            "name": "@log",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/var/cache/pacman/pkg",
                            "name": "@pkg",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/.snapshots",
                            "name": "@.snapshots",
                            "nodatacow": false
                        }
                    ]
                },
                "encrypted": false,
                "filesystem": {
                    "format": "btrfs",
                    "mount_options": [
                        "compress=zstd"
                    ]
                },
                "mountpoint": null,
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
```

**Comment by Torxed** [comment]
I think I found the issue. It appears the script executed is using `guided` from the installed `archinstall` rather than the git clone in the ISO that I'm used to.

**Review by Torxed — APPROVED** [review]

**Comment by Torxed** [comment]
Great work @svartkanin!

**Comment by svartkanin** [comment]
Awesome, thanks for testing it all

**Pull request merged**
