### PR TITLE
Change usage `lsblk` to `blkid` where possible. And general improvements to disk handling.

### PR DESCRIPTION
**Pull request by Torxed**
I'll add a deprecated legacy function named `all_disks()` once the changes to `all_blockdevices()` have been identified and working. This is so that anyone using the function in their dotfiles can keep using it for a version or two.

But overall the return values of the function should be more strict and work better.
The downside is that the information returned is completely different if used in-depth.

There for even with a legacy function, some information on the actual return-data is different.
It no longer returns a generic `BlockDevice()` but instead a `Partition()` for partitions and `BlockDevice()` for "actual" block devices *(parent devices, `/dev/sda` for instance)'.

Long plan: Make it return a custom object like `LoopDev`, `CryptDev`, `RaidDev` etc for specific devices found.
It will make life a lot easier when dealing with different types such as raids, which currently is "confused" for being just a regular block dev.

Main goal here tho is:
 * Make sure we don't "miss" a device after it's being created *(currently, `/dev/sda2` doesn't always show up in `all_disks()` right after being created)*
 * Make the return values more strict, perhaps even use `@dataclass` in the future.
 * Make information more true. Instead of populating it with our own `type: raid` we use `blkid` information directly without manipulation.

# Breaking changes:
 * `archinstall.get_partitions_in_use()` now returns a `dict`, previously it was just a `list`. But this speeds lookups up quite a bit and makes other logic a lot simpler/cleaner to maintain as the result is `{"/mountpoint": device}`.
 * `archinstall.all_disks()` has been deprecated and slightly modified. Should behave roughly as expected or with minimal effort of fixing.
 * `archinstall.BlockDevice()` previous variable `.mountpoint` is now a `@property` without a `setter`. This is because it now uses live data reported by `findmnt` which should be more fault tolerant to corrupt cache data. But that means any attempt to do `block_dev.mountpoint = "/somewhere"` will fail as it's a read-only variable.
 * `archinstall.all_blockdevices()` replaces `archinstall.all_disks()` and it now returns specific types for the different blockdevices.
 * `archinstall.split_bind_name()` will be deprecated, we can use `Partition().subvolumes` instead and get the bind name from there.

# New features
 * `archinstall.add_bootloader()` is now a router to three new functions: `.add_systemd_bootloader()`, `.add_grub_bootloader()` and `.add_efistub_bootloader()` which behaves the same as before, but the logic is divided into duties.
 * `MapperDev` has been introduced to split `BlockDevice` anonymous setups
 * `DMCryptDev` has been introduced to split `BlockDevice` anonymous setups
 * `BtrfsSubvolume` has been introduced to split `BlockDevice` anonymous setups
 * `Partition().subvolumes` returns any potential btrfs subvolumes
 * `archinstall.blkid()` has been added to get a dictionary structure from `blkid -o export` results
 * `archinstall.get_loop_info()` has been added to return information returned from `losetup`
 * `archinstall.enrich_blockdevice_information()` has been added and enriches `blkid` and `losetup` information.
 * `archinstall.uevent()` was added and process `blkid -o export` and `/sys/class/block/x/uevent` data into a dictionary structure
 * `archinstall.get_blockdevice_uevent()` returns `/sys/class/block/x/uevent` data, returned from `.uevent()` for a blockdevice
 * `archinstall.get_parent_of_partition()` returns `/dev/sda` for `/dev/sda1` for instance, and takes a `pathlib.Path` object, and resolves symlinks etc.
 * `archinstall.find_mountpoint()` takes a device path, like `/dev/sda1` and returns the mountpoint information for the device
 * `archinstall.get_all_targets()` returns a complete recursively parsed list of mountpoint targets from a struct returned by `findmnt`
 * `archinstall.get_subvolumes_from_findmnt()` takes a `findmnt` result structure and finds any potential subvolumes
 * `archinstall.get_subvolume_info()` returns potential `btrfs subvol show` information from a given path

# Bug fixes
 * `SysCommandWorker()` now returns the last 500 bytes of an error, rather than the first 500.
 * `log()` does not output `logger.DEBUG` level messages by default any more, instead `--debug` must be given on start.
 * `archinstall.select_harddrives()` only shows `BlockDevice` objects.

### CODE REVIEW

**Comment by Torxed** [comment]
[525d346](https://github.com/archlinux/archinstall/pull/949/commits/525d346d38a80538bcaf80a871fc71dfecf90a07) is a massive commit. Will document the changes accordingly.

It contains several breaking changes but creates distinct differences between disk-objects.
It simplifies a lot of "lookups" and removes the need to guess weither a device is a `DMCrypt` device, `Partition` of `BlockDevice`, in short, this ugly beast is now gone: https://github.com/archlinux/archinstall/blob/3c650e9aca34edc3b986dd7ef154b4307634f6a3/archinstall/lib/disk/helpers.py#L257-L279

And instead we can do: https://github.com/archlinux/archinstall/blob/525d346d38a80538bcaf80a871fc71dfecf90a07/archinstall/lib/disk/helpers.py#L329-L334

**Comment by Torxed** [comment]
Installer goes through "without errors".
But it won't be able to de-crypt the luksvolume, so probably a PARTUUID that's wrong.

Once that's solved, the PR is ready for a merge.

**Comment by Torxed** [comment]
Error after booting encrypted volumes with BTRFS subvolumes:
screenshot

**Comment by Torxed** [comment]
> I've done a try. In my case it lacks the subvol entry in the systemd-bootctl file (/boot/loader/entries/2*.conf I thought this was solved some time ago. I simply added at `òptions` in the file `rootflags=subvol=@` and has started at the first try The code at Installer.add_bootloader (line 738 ff.) looks OK as long as root_partition.path has the subvolume reference _Updated. It doesn't. There is where to look at how it is filled nowadays, or search for another way to ascertain you are running / from a subvolume_

Ah, yea that might be the thing that's missing.
I'm thinking of creating a new "block device" called BtrfsSubvolume that either inherits `Partition` or simply has a `@property` that defines `.partition` when we need it.
This is to avoid dealing with this "advanced" meta functionality via strings.

That way we can do `if type(partition) is BtrfsSubvolume` we can more easily detect the need for `rootflags=subvol=@`

**Comment by Torxed** [comment]
You are correct btw, and I appreciate the quick response.
It's the `rootflags=subvol=X` that's missing. Taken from the v2.3.1:
screenshot

**Comment by Torxed** [comment]
There's also still some confusion in the logic when it hits a non-encrypted partition on a loopdevice.
`/dev/loop0p2` for instance:
```
DEVNAME=/dev/loop0p2
UUID=d2d57199-df63-4853-b121-87776fa76668
UUID_SUB=417cafc1-525a-4776-b956-ca5251bf2e56
BLOCK_SIZE=4096
TYPE=btrfs
PARTLABEL=primary
PARTUUID=9fd512f3-d426-42f4-ab07-afec41b66b98
```
Mainly because the loop device partition also has `UUID_SUB` which I incorrectly assumed only subvolumes and/or encrypted devices would have. But naturally loopdevices have it too. So I'll need to re-work the detection logic for "is this a DM-crypt device?"

**Comment by Torxed** [comment]
Not sure why, but `mkinitcpio -P` fails during `__exit__` of `Installer()`.
Other than that, and the language thing at the end.. I think it looks more ready than before.

Will try to see why those two errors occur, and then run some tests on encrypted, non encrypted, grub and systemd and if those passes. This will get merged in :)

**Comment by Torxed** [comment]
System now boots, with encryption and subvolumes.
However, I'm getting a really annoying `flake8` issue that I can't figure out: https://github.com/archlinux/archinstall/runs/5106607654?check_suite_focus=true

```
Run flake8
./archinstall/lib/disk/helpers.py:22[4](https://github.com/archlinux/archinstall/runs/5106607654?check_suite_focus=true#step:7:4):3: F[8](https://github.com/archlinux/archinstall/runs/5106607654?check_suite_focus=true#step:7:8)41 local variable 'error' is assigned to but never used
		except SysCallError as error:
		^
1     F841 local variable 'error' is assigned to but never used
1
Error: Process completed with exit code 1.
```

The variable is used, not one line later...?

**Comment by Torxed** [comment]
Muted errors, tested:
 * systemd-boot + encryption + btrfs subvolumes
 * systemd-boot + btrfs subvolumes
 * systemd-boot + ext4
 * GRUB (UEFI) + encryption + btrfs subvolumes
 * GRUB (UEFI) + btrfs subvolumes
 * GRUB (UEFI) + ext4

Not working:
 * GRUB (BIOS) + encryption + btrfs subvolumes
 * GRUB (BIOS) + btrfs subvolumes
 * GRUB (BIOS) + ext4

Essentially nothing with GRUB on BIOS works, but partition is marked as bootable:
screenshot

**Comment by Torxed** [comment]
Seems to be related to being installed on the second drive.
Maybe only on VM's as well using the qemu default BIOS.

If I install to the first drive, it looks like it's working..

**Comment by wllacer** [comment]
@torxed. I did a quick try to the all_blockdevices() call:
THis is the result I get from a `pprint(archinstall.all_blockdevices(partitions=True))` 
```
udo python test.py
Could not locate mount information for /dev/loop0p1: ['/usr/bin/findmnt', '--json', '-R', '/dev/loop0p1'] exited with abnormal exit code [256]: b''
Could not locate mount information for /dev/loop0p2: ['/usr/bin/findmnt', '--json', '-R', '/dev/loop0p2'] exited with abnormal exit code [256]: b''
Could not locate mount information for /dev/sda2: ['/usr/bin/findmnt', '--json', '-R', '/dev/sda2'] exited with abnormal exit code [256]: b''
{'/dev/loop0': BlockDevice(/dev/loop0, size=8.0GB, free_space=1031kB+1049kB+1032kB, bus_type=None),
 '/dev/loop0p1': Could not locate mount information for /dev/loop0p1: ['/usr/bin/findmnt', '--json', '-R', '/dev/loop0p1'] exited with abnormal exit code [256]: b''
Partition(path=/dev/loop0p1, size=0.5, PARTUUID=88c98d3b-203d-4d9f-80b5-45d1f8b7c33a, fs=vfat),
 '/dev/loop0p2': Could not locate mount information for /dev/loop0p2: ['/usr/bin/findmnt', '--json', '-R', '/dev/loop0p2'] exited with abnormal exit code [256]: b''
Partition(path=/dev/loop0p2, size=7.5, PARTUUID=770da30d-7e5b-4a20-96fc-6de271ded7cf, parent=/dev/loop0, fs=crypto_LUKS),
 '/dev/sda': BlockDevice(/dev/sda, size=465.8GB, free_space=4177kB+7680B, bus_type=sata),
 '/dev/sda1': Partition(path=/dev/sda1, size=1.0, PARTUUID=b941ab7e-ec60-4cbc-8365-1a7558d20f1d, fs=vfat, mounted=/boot),
 '/dev/sda2': Could not locate mount information for /dev/sda2: ['/usr/bin/findmnt', '--json', '-R', '/dev/sda2'] exited with abnormal exit code [256]: b''
Partition(path=/dev/sda2, size=8.0, PARTUUID=9ea1e7b3-b2ca-4dc2-a10f-cb8653909012, fs=swap),
 '/dev/sda3': Partition(path=/dev/sda3, size=456.8, PARTUUID=15035603-14bd-4b34-9d15-ddd4a0fae9f3, fs=btrfs, mounted=/),
 '/dev/sr0': BlockDevice(/dev/sr0, size=1.0GB, free_space=, bus_type=sata)}

```
The errors aren't (two partitons not mounted and one is swap). Is this intended or the output can be tuned so they don't appear.
/dev/sda3 is a btrfs partition with subvolumes. What call must i do to get, at least, the mounted subvolumes?

The process feels a lot faster now

**Comment by dylanmtaylor** [comment]
> Seems to be related to being installed on the second drive. Maybe only on VM's as well using the qemu default BIOS.
> 
> If I install to the first drive, it looks like it's working..

It might be related to how BIOS handles drive selection. Maybe a bootable flag or something?

**Comment by Torxed** [comment]
> @Torxed. I did a quick try to the all_blockdevices() call: THis is the result I get from a `pprint(archinstall.all_blockdevices(partitions=True))`
> 
> ```
> udo python test.py
> Could not locate mount information for /dev/loop0p1: ['/usr/bin/findmnt', '--json', '-R', '/dev/loop0p1'] exited with abnormal exit code [256]: b''
> Could not locate mount information for /dev/loop0p2: ['/usr/bin/findmnt', '--json', '-R', '/dev/loop0p2'] exited with abnormal exit code [256]: b''
> Could not locate mount information for /dev/sda2: ['/usr/bin/findmnt', '--json', '-R', '/dev/sda2'] exited with abnormal exit code [256]: b''
> {'/dev/loop0': BlockDevice(/dev/loop0, size=8.0GB, free_space=1031kB+1049kB+1032kB, bus_type=None),
>  '/dev/loop0p1': Could not locate mount information for /dev/loop0p1: ['/usr/bin/findmnt', '--json', '-R', '/dev/loop0p1'] exited with abnormal exit code [256]: b''
> Partition(path=/dev/loop0p1, size=0.5, PARTUUID=88c98d3b-203d-4d9f-80b5-45d1f8b7c33a, fs=vfat),
>  '/dev/loop0p2': Could not locate mount information for /dev/loop0p2: ['/usr/bin/findmnt', '--json', '-R', '/dev/loop0p2'] exited with abnormal exit code [256]: b''
> Partition(path=/dev/loop0p2, size=7.5, PARTUUID=770da30d-7e5b-4a20-96fc-6de271ded7cf, parent=/dev/loop0, fs=crypto_LUKS),
>  '/dev/sda': BlockDevice(/dev/sda, size=465.8GB, free_space=4177kB+7680B, bus_type=sata),
>  '/dev/sda1': Partition(path=/dev/sda1, size=1.0, PARTUUID=b941ab7e-ec60-4cbc-8365-1a7558d20f1d, fs=vfat, mounted=/boot),
>  '/dev/sda2': Could not locate mount information for /dev/sda2: ['/usr/bin/findmnt', '--json', '-R', '/dev/sda2'] exited with abnormal exit code [256]: b''
> Partition(path=/dev/sda2, size=8.0, PARTUUID=9ea1e7b3-b2ca-4dc2-a10f-cb8653909012, fs=swap),
>  '/dev/sda3': Partition(path=/dev/sda3, size=456.8, PARTUUID=15035603-14bd-4b34-9d15-ddd4a0fae9f3, fs=btrfs, mounted=/),
>  '/dev/sr0': BlockDevice(/dev/sr0, size=1.0GB, free_space=, bus_type=sata)}
> ```
> 
> The errors aren't (two partitons not mounted and one is swap). Is this intended or the output can be tuned so they don't appear. /dev/sda3 is a btrfs partition with subvolumes. What call must i do to get, at least, the mounted subvolumes?
> 
> The process feels a lot faster now

The output should be muted in the latest commit, unless `—debug` is set.

you can run:
```python
import archinstall

for subvolume in archinstall.Partition(“/dev/sda3”, archinstall.BlockDevice(“/dev/sda”)).subvolumes:
    print(subvolume)
```
Keep in mind that if /dev/sda3 is a encrypted volume the above does not apply, in which case you need to use `archinstall.MapperDev(“devname”)` instead of Partition.

**Comment by wllacer** [comment]
Many thanks. I'll try It ASAP

**Comment by Torxed** [comment]
Let me know how the testing went, and I'll merge this if nothing odd comes up :)

I'm planning on making `BlockDevice()` an automatic instance, so you don't have to pass it in. But I want this code to settle first and get some real world users testing this new code before I commit to that. That would make it so you can do `archinstall.Partition("/dev/sda1")` without having to manually assign a `archinstall.BlockDevice()`.

**Comment by wllacer** [comment]
Sorry for the delay. Something seems still wrong. I tr
Last commit in my copy is
```
commit 72925e7668e08f87efc172f7c69177dcced876bc (HEAD -> block_devices, upstream/torxed-fix-all_disks)
Merge: 03a4cd2 feffa69
Author: Anton Hvornum <anton@hvornum.se>
Date:   Tue Feb 8 21:08:05 2022 +0100

    Merged master into branch
```
If i execute 
```python
result = archinstall.all_blockdevices(partitions=True)
for res in sorted(result):
	print(res,'>',type(result[res]),result[res])
```
I get (and a lsblk to compare)
```
werner@xerneas archinstall]$ python test.py
Not enough permission to place log file at /var/log/archinstall/install.log, creating it in /home/werner/projects/archinstall/install.log instead.
/dev/loop0 > <class 'archinstall.lib.disk.blockdevice.BlockDevice'> BlockDevice(/home/werner/vms/testimage.img, size=8.0GB, free_space=, bus_type=None)
/dev/loop0p1 > <class 'archinstall.lib.disk.blockdevice.BlockDevice'> BlockDevice(None, size=0.5GB, free_space=, bus_type=None)
/dev/loop0p2 > <class 'archinstall.lib.disk.blockdevice.BlockDevice'> BlockDevice(None, size=7.5GB, free_space=, bus_type=None)
/dev/sda > <class 'archinstall.lib.disk.blockdevice.BlockDevice'> BlockDevice(/dev/sda, size=465.8GB, free_space=, bus_type=sata)
/dev/sda1 > <class 'archinstall.lib.disk.blockdevice.BlockDevice'> BlockDevice(None, size=1.0GB, free_space=, bus_type=None)
/dev/sda2 > <class 'archinstall.lib.disk.blockdevice.BlockDevice'> BlockDevice(None, size=8.0GB, free_space=, bus_type=None)
/dev/sda3 > <class 'archinstall.lib.disk.blockdevice.BlockDevice'> BlockDevice(None, size=456.8GB, free_space=, bus_type=None)
/dev/sr0 > <class 'archinstall.lib.disk.blockdevice.BlockDevice'> BlockDevice(/dev/sr0, size=1.0GB, free_space=, bus_type=sata)
[werner@xerneas archinstall]$ lsblk
NAME      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0       7:0    0     8G  0 loop 
├─loop0p1 259:0    0   511M  0 part 
└─loop0p2 259:1    0   7,5G  0 part 
sda         8:0    0 465,8G  0 disk 
├─sda1      8:1    0  1020M  0 part /boot
├─sda2      8:2    0     8G  0 part [SWAP]
└─sda3      8:3    0 456,8G  0 part /var
                                    /home
                                    /opt
                                    /
sr0        11:0    1  1024M  0 rom  

```
As you can see it doesn't return Partition object. It seems it takes a wrong turn at lines 243ff of the add_blockdevices. I still can not pinpoint where it takes the wrong turn (too many new data to control )

**Comment by Torxed** [comment]
You need to run your test with root privileges as it's disk operations.
Try:
```
sudo python test.py
```

**Comment by Torxed** [comment]
Here's my difference using your code:

screenshot

**Comment by wllacer** [comment]
Ouch... Clearly, i have to learn how to use it correctly but it is a godsend for me.

**Comment by Torxed** [comment]
Merged. Any fixes to this can be implemented later. I want to get this in before more forks of master occur, making it easier to merge those later. And I think this is in a more stable condition than master currently, so it should do more good than harm.

**Comment by wllacer** [comment]
there is only one thing i'd wish, and i don't see.  And is to have easy access to all the information the routine gathers creating the information dictionary. I've seen that it is present for BlockDevices at Blockdevice.info, but can't see an equivalent at Partition,-haven't checked  DMCryptDev. I know some part is dynamic, and could be extracted on the fly, but a Partition.info would be a nice addition. Having direct access with a simple `partition.info['whatever']` would be ideal
```
sys/class/block/loop0 {'/dev/loop0': {'path': '/dev/loop0', 'PATH': '/dev/loop0', 'PTUUID': 'b8e8c4a1-9a59-4d40-9082-014f06f9f3e3', 'PTTYPE': 'gpt', 'MAJOR': '7', 'MINOR': '0', 'DEVNAME': 'loop0', 'DEVTYPE': 'disk', 'DISKSEQ': '4'}}

/sys/class/block/sda3 {'/dev/sda3': {'path': '/dev/sda3', 'PATH': '/dev/sda3', 'UUID': '4451fb0e-b5b5-45ed-b2f7-8d34015295b0', 'UUID_SUB': '0fab6bda-02d5-4348-ab90-e3c36b2e4862', 'BLOCK_SIZE': '4096', 'TYPE': 'btrfs', 'USAGE': 'filesystem', 'PART_ENTRY_SCHEME': 'gpt', 'PART_ENTRY_NAME': 'Primary', 'PART_ENTRY_UUID': '15035603-14bd-4b34-9d15-ddd4a0fae9f3', 'PART_ENTRY_TYPE': '0fc63daf-8483-4772-8e79-3d69d8477de4', 'PART_ENTRY_NUMBER': '3', 'PART_ENTRY_OFFSET': '18874368', 'PART_ENTRY_SIZE': '957898752', 'PART_ENTRY_DISK': '8:0', 'MAJOR': '8', 'MINOR': '3', 'DEVNAME': 'sda3', 'DEVTYPE': 'partition', 'DISKSEQ': '1', 'PARTN': '3', 'PARTNAME': 'Primary'}}
/sys/class/block/sda1 {'/dev/sda1': {'path':
```

**Comment by Torxed** [comment]
That's a good suggestion. We'll add a separate PR for that, adding to this functionality.
This PR was getting out of hand in terms of changes, and it touched so many places I was afraid of making another fork of master before this got in.

I'll add that, and I'll add a warning if used on a qemu-virtual-machine and GRUB being installed under BIOS on a second drive. As that appears to cause issues.

**Pull request merged**
