### PR TITLE
Revise packages in Budgie profile

### PR DESCRIPTION
**Pull request by serebit**
## PR Description:

This PR revises the list of packages included in the Budgie profile.

- The Arc GTK theme and Papirus icon theme are the schema defaults for the `budgie-desktop` package (Adwaita does not support Budgie), and thus including their packages sets them in the desktop automatically
- The `gnome` group has been replaced with Nemo and MATE Terminal, as most of that group was unnecessary to include in a minimal Budgie installation
- `budgie-desktop-view` provides desktop icon support for users who want the feature

These changes result in a Budgie installation more reflective of current upstream recommendations.

## Tests and Checks
- [x] I have tested the code!<br>

### CODE REVIEW

**Comment by Torxed** [comment]
Thanks for the PR.
I assume this is per discussions I saw the other day in Arch internal?

I'd be happy to merge this, but would you mind if I tweak it a bit so that `network-manager-applet` only gets installed if NM was the selected network choice in the global menu? :)

**Comment by serebit** [comment]
Yeah, this is a result of that discussion.

That sounds ideal, go right ahead!

**Comment by dylanmtaylor** [comment]
I also think that network manager should be dropped. I'm not sure about some of the others, it feels a bit opinionated. Should we ship the optional desktop icons? Which terminal/file manager should we use? Why not gnome-terminal and nautilus, as mate is based off of a really old codebase? Overall, this is probably a step in the right direction.

**Comment by serebit** [comment]
Point by point:

- The network manager applet should be installed if NetworkManager is selected by the user, but not otherwise. I wasn't aware that this was possible to automate, but I'm in favor of it.
- Technically budgie-desktop-view is optional for Budgie to function, which is why it's an optional dep in the package, but including them allows the user to simply enable desktop icons if they want them and it doesn't take up much disk space. It's in service of providing a more complete Budgie with the profile.
- It is opinionated, but it sort of has to be. I'm one of the developers of Budgie, and there is no officially recommended file manager or terminal—downstreams are free to choose what they feel is most appropriate. For example, last I checked, Solus ships Nautilus and GNOME Terminal, but Fedora's work-in-progress Budgie spin developed by the Budgie BDFL will ship Caja and MATE Terminal instead. I believe Nemo and MATE Terminal are more reasonable defaults for the Budgie profile than Nautilus and GNOME Terminal given that they both use GTK3 and support GTK widget themes like the rest of the desktop.

**Comment by serebit** [comment]
Updated and tested the code by modifying the profile .py file in a live environment. Works perfectly.

**Comment by Torxed** [comment]
Thank you for these fixes, apologies that it took so long to merge.
Wanted to get #1557 out of the way first to make sure we're back to stable again.

**Pull request merged**
