### PR TITLE
Combine KDE Wayland and Xorg installations into one profile.

### PR DESCRIPTION
**Pull request by dylanmtaylor**
# Pull Request Template

Make sure you've checked out the [contribution guideline](https://github.com/archlinux/archinstall/blob/master/CONTRIBUTING.md).<br>
Most of the guidelines are not enforced, but is heavily encouraged.

## Description

Please include a summary of the change and which issue is fixed.<br>
It is also helpful to add links to online documentation or to the implementation of the code you are changing.

## Bugs and Issues

If this pull-request fixes an issue or a bug, please mention the issues with the approriate issue referece *(Example: &#35;8)*.

## How Has This Been Tested?

If possible, mention any tests you have made with the current code base included in the pull-requests.<br>
Any core-developer will also run tests, but this helps speed things up. Below is a template that can be used:

As an example:

**Test Configuration**:
* Hardware: VirtualBox 6.1
* Specific steps: Ran installer with additional packages `nano` and `wget`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code to the best of my abilities
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where possible/if applicable

### CODE REVIEW

**Comment by advaithm** [comment]
@dylanmtaylor this is missing the warning about nvidia being very very buggy on plasma wayland.

**Comment by Torxed** [comment]
> @dylanmtaylor this is missing the warning about nvidia being very very buggy on plasma wayland.

After sleeping on it, adding a warning might be confusing for users who might think their chosen installation will not work some how. Instead, we should make sure xorg is the default *(for now)* if we detect nVidia. That way we don't confuse people - but they can still choose wayland if they know what they're doing. And hopefully those that do know this also do their research when things go sideways.

I'll just check which is the default with this setup when the users come to the greeter before i merge. If it's xorg anyway it's a solid merge for now.

**Comment by Torxed** [comment]
I've tested the PR and it works great. No issues (not really a surprise).
I do wish we fix this first tho: https://github.com/archlinux/archinstall/issues/163#issuecomment-813945634

Would that be possible @dylanmtaylor?

**Comment by dylanmtaylor** [comment]
I think that this PR is more or less included in @advaithm's PR, so I'm closing this for removing confusion.

**Pull request closed without merging**
