### PR TITLE
Support CJK text alignment

### PR DESCRIPTION
**Pull request by yetist**
## PR Description:

Support CJK text alignment

### CODE REVIEW

**Comment by yetist** [comment]
Before:
image

After:
image

**Review by Torxed — APPROVED** [review]

**Comment by Torxed** [comment]
Well done on all of this!

**Comment by svartkanin** [comment]
Should we maybe rename the `clk` to something more meaningful? If this turns out to affect other languages in the future then the name is not inclusive and both specific at the same time. 
Would `unicode` make more sense here as that's what it's doing?

**Comment by yetist** [comment]
> Should we maybe rename the `clk` to something more meaningful? If this turns out to affect other languages in the future then the name is not inclusive and both specific at the same time. Would `unicode` make more sense here as that's what it's doing?

How about using the following names?
`_count_cjk_chars()` -> `_count_wchars()`
`cjk_ljust()` -> `unicode_ljust()`
`cjk_rjust()` -> `unicode_rjust()`

**Comment by svartkanin** [comment]
Yes that'd be great

**Review by Torxed — APPROVED** [review]

**Pull request merged**
