### PR TITLE
Implement chroot prompt after successful installation

### LINKED ISSUE #225: After install, prompt the user if they want to chroot into the installation
I think it would be a good idea to add a prompt to ask the user if they want to chroot into the newly created installation after the installation steps are executed.

For instance in pseudo-code, 

```
choice = input("Would you like to chroot into the newly created installation? [Y/n]")
if choice.lower() == 'y':
     execute('arch-chroot /mnt');
```

### PR DESCRIPTION
**Pull request by dylanmtaylor**
This allows users to chroot into a newly installed system so they can perform further configuration and customization. 

Closes #225

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
Seems to work, let me test this one more time with the latest ISO before merging in.

VirtualBox_Arch Linux_12_04_2021_09_22_18

**Comment by dylanmtaylor** [comment]
Tested working and ready to go in

VirtualBox_Arch Linux_12_04_2021_09_51_08

**Comment by dylanmtaylor** [comment]
Seems to still work after moving the choice to guided.

VirtualBox_Arch Linux_12_04_2021_10_41_01

**Comment by Torxed** [comment]
Very nice, much appreciated change!

**Pull request merged**
