### PR TITLE
po: update Tamil translation

### PR DESCRIPTION
**Pull request by kbdharun**
## PR Description:

Update Tamil translations and add translations for untranslated strings.

## Tests and Checks
- [ ] I have tested the code!<br>

### CODE REVIEW

**Review by Torxed — APPROVED** [review]

**Comment by Torxed** [comment]
@svartkanin not sure what's failing in the `local_generate` step, can't see any output of why it would fail. But approving as the PR appears good.

**Comment by svartkanin** [comment]
Let me have a look, yeah the output is definitely not good, I'll update that

**Comment by svartkanin** [comment]
@Torxed this should be clearer now 
image

**Comment by kbdharun** [comment]
Seems like there are a few new strings, will create a PR for it soon.

**Pull request merged**
