### PR TITLE
removed post_install hook for kde plasma

### PR DESCRIPTION
**Pull request by advaithm**
🚨 PR Guidelines:

# New features *(v2.2.0)*

Merge new features in to `torxed-v2.2.0`.<br>
This branch is designated for potential breaking changes, added complexity and new functionality.

# Bug fixes *(v2.1.4)*

As @dylanmtaylor  using mv can break stuff during updates. Until we find a better way I think this is the best choice

# Describe your PR

this comments out the post install hook in the kde profile

# Testing

Any new feature or stability improvement should be tested if possible.
Please follow the test instructions at the bottom of the README.

*These PR guidelines will change after 2021-05-01, which is when `v2.1.4` gets onto the new ISO*

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
To clarify, as there isn't much context in this PR, I noticed that the default behavior isn't very reliable - it seems that SDDM chooses a default based on the filename (?) from what @advaithm discovered in how Fedora sets the default session here: https://src.fedoraproject.org/rpms/plasma-workspace/blob/rawhide/f/plasma-workspace.spec#_701

The issue is that if we move files (as we are not packagers, and have no control over where updates for session files get written), we might inadvertantly break updating the plasma-workspace or plasma-wayland-session packages. This could cause some weird behavior that could either require user intervention (specific to the way we install KDE, not general to Arch and therefore not listed on the manual interventions newsletter), or cause really strange behavior like two different X11 sessions in the SDDM list, one from when the system was installed, and another from when the package was updated.

As a matter of exercising an abundance of caution, we agreed that until we find a better way to set a default (and it looks like one cannot be set in sddm.conf), it is best to NOT attempt to rename files. It is easy enough for the user to select their desired session from a drop-down on first boot that removing this selection is not a big deal.

**Comment by dylanmtaylor** [comment]
I checked out this commit from live media and tested it.

Checking it's the right commit:
VirtualBox_ArchLinux_07_04_2021_22_17_51

After installation (no default session question asked):
VirtualBox_ArchLinux_07_04_2021_22_42_33

Booted to a working SDDM:
VirtualBox_ArchLinux_07_04_2021_22_43_11

Notably, Wayland seemed to be the default.

**Comment by advaithm** [comment]
Hmmm no idea why

**Comment by dylanmtaylor** [comment]
> Hmmm no idea why

So, I have an idea. Why not just do something like this and let the user set the default themselves?

```
def _post_install(*args, **kwargs):
	print("After booting, you can choose between Wayland and Xorg using the drop-down menu")
	return True
```

**Comment by advaithm** [comment]
Sure I think that's the best move for now

**Review by dylanmtaylor — APPROVED** [review]
Looks good to me

**Pull request merged**
