### PR TITLE
Flexible menu 2

### PR DESCRIPTION
**Pull request by wllacer**
This is an replacement of PR #866 

This is **EXPERIMENTAL** code. It is more a working sample of how we could create a general selection menu framework, than a full blown solution; and can be a blueprint for exploration. 

What we have done is to extend the, otherwise excellent, code of @svartkanin for defining a *global selection menu*, with the 
intent of making it a reusable generic tool. Mostly, we have extracted/isolated all code which is directly dependent of Archinstall and the guided.py script, and done a couple of juditious (IOHO) extensions, so the code becomes as generic as possible

<h2> What we have done </h2>

* We have created a base class **GeneralMenu** which holds only the routines needed to handle an arbitrary menu backed by a data area (dictionary) for which, a menu entry is a first level item in the dict. Each menu entry is managed by a **Selector** object. The class is defined as a *context manager* (has \__enter__ and \__exit__ methods).

* We defined following signature for GeneralMenu

```python
	def __init__(self,
			data_store :dict = None,)
```
* *  **data_store** is the area (dictionary) where the selections will be stored, and transferred from/to surrounding code.

* * We have defined following public methods to the class
* * * enable
* * * run
* * * exec_option
* * * option
* * * synch
* * * list_enabled_options
* * * set_option
* * * set_mandatory
* * * mandatory_overview
* * * pre_callback
* * * post_callback
* * * exit_callback

* * This methods are abstract and have to be implemented for every realization of GeneralMenu
* * * _setup_selection_menu_options. Define which menu entries are to be displayed
* * * pre_callback. Code to be executed BEFORE any menu action
* * * post_callback Code to be executed AFTER any menu action
* * * exit_callback Code to be executed at the END of the menu processing

* * We expect some methods to be overloaded in child classes. Those are expected to invoke their parent implentation at one point or another
* * * \__init__  Basically, to prepare a data area to the flat dictionary standard needed for the menu. A call to super().\__init__ is necessary there, and it should be the last statement at the method (otherwise option definition could not work correctly)
* * \__enter__

* * This methods could be overloaded, but the callback methods in the  are thought for personalizing its behaviour under normal circumstances
* * * \__exit__ (use *exit_callback* for processing. Overload for error management)
* * * run  (use *pre_/post_callback*)

* We have expanded the signature of Selector:

```python
		exec_func :Callable = None,
		preview_func :Callable = None,
		mandatory :bool = False

```

* * Till now we had two callables, one for formating the line (display) and one for the selection routine. When the actions for the Install and Abort options were taken off GlobalMenu, we thougth that a further function, to be executed to ascertain if the menu had to exit -and whatever action it would be of interest-, was better linked to each option, so we could even have several "action" options in the same menu, so we created the **exec_func** callable, which will be executed just before checking if all the mandatory parameters are filled.

* * The **preview_func** is to create routines which can handle the needs of the *preview* action of *simple_menu* (a window which shows with detail an option). Still unimplemented

* * We have introduced a new property for the options at *Selector*: **mandatory**. A mandatory option is enabled by default. The menu loop can not be exited if any mandatory option is still has not been selected. The mandatory status can be changed on the fly. Not all the coherence controls could be reduced to mandatory, so the need for user-exits

* As we cleaned the dependent code, we moved the definition of the options outside the base class. We left an empty method **_setup_selection_menu_options**, to be overloaded for those that wish to subclass it and make an "static" -or preloaded- menu. For the most daring, the use of the method  **set_option** is available to define an option whenever is needed

* We have created a few methods to serve the need of the new functionality, or to simplify the programming outside the class code

* As a bonus, the indicator of missing conditions at the Install entry, is now updated after each interaction with the menu

<h2> Usage </h2>

We recommend to create a subclass for each different multiple options menu you might need in the application.
We have defined a standard subclass **GlobalMenu** which is the basic frontend of archinstall
and used at the default installation script of Archinstall (**guided.py**), whose code we haven't touched.
You might want to have a look at it, as a sample of use. This time we have decided to opt for keeping the options definition and auxiliary functions inside the class, as overloads or extended functionality of the GeneralMenu class. Unlike what i thought in my previous take, it helps to keep them thightly controled, and thus, easing maintenace.

For **only_hd.py** we have opted for subclassing GlobalMenu rather than the GeneralMenu. It was the logical step

```python

class OnlyHDMenu(archinstall.GlobalMenu):
	def _setup_selection_menu_options(self):
		super()._setup_selection_menu_options()
		options_list = []
		mandatory_list = []
		options_list = ['harddrives', 'disk_layouts', '!encryption-password','swap']
		mandatory_list = ['harddrives']
		options_list.extend(['install','abort'])

		for entry in self._menu_options:
			if entry in options_list:
				# for not lineal executions, only self.option(entry).set_enabled and set_mandatory are necessary
				if entry in mandatory_list:
					self.enable(entry,mandatory=True)
				else:
					self.enable(entry)
			else:
				self.option(entry).set_enabled(False)
		self._update_install()

	def _missing_configs(self):
		""" overloaded method """
		def check(s):
			return self.option(s).has_selection()

		_, missing = self.mandatory_overview()
		if check('harddrives'):
			if not self.option('harddrives').is_empty() and not check('disk_layouts'):
				missing += 1
		return missing

...

def ask_user_questions():
    with OnlyHDMenu(data_store=archinstall.arguments) as menu:
		menu.run()
```
Note that the last routine could equally have been written
```
def ask_user_questions():
    OnlyHDMenu(data_store=archinstall.arguments).run
```

For the script **swiss.py**, which is a kind of technology demostrator, we have expanded that code, allowing for different workflows into just one class. A note of interest is how we execute the menu:

```python
	with MyMenu(data_store=archinstall.arguments,mode) as global_menu:

		if mode == 'lineal':
			for entry in global_menu.list_enabled_options():
				if entry in ('install','abort'):
					continue
				global_menu.exec_option(entry)
				archinstall.arguments[entry] = global_menu.option(entry).get_selection()
		else:
			global_menu.set_option('install',
							archinstall.Selector(
								global_menu._install_text(mode),
								exec_func=lambda x: True if global_menu._missing_configs(mode) == 0 else False,
								enabled=True))

			global_menu.run()
```
Two interesting points in this code
* Before executing the code, we have changed a menu option from its default behaviour via the **set_option** method
* In the part under `mode=='lineal'`, instead of showing the menu, what we get is a sequence of selection screens (the same to be executed in the menu). The GeneralMenu object controls the execution (and integrity checks) but does not appear.

Also at swiss.py, executed when using the *advanced* parameter you get another menu, this time, with absolutely no relation to the original one. You can look there at the code

```
                                                                                                                                                Set/Modify the below options

Use ESC to skip


> Activate NTP                        SET: Y
  Excution mode                       SET: full
  general (LC_ALL) locale
  Character set locale                SET: es_ES.utf8
  Numeric values locale               SET: C
  Time Values locale                  SET: C
  text messages locale                SET: C
  sort order locale                   SET: es_ES.utf8
  Continue
(Press "/" to search)
```

<h2> TODO list and possible alternates </h2>.

* I'm working in designing some menus to manage the btrfs. Will see what comes out of it

* Implement a preview process, at least for *disk_layouts*

* Implement a visual marker for mandatory options

* I'm not very partial to the current location of GlobalMenu, due to the use of the `ìmport archinstall`in a *lib* location

<h2> Testing

Beside the usual bug hunting, it could be of interest to try to create user own menus with this infraestructure, to find missing functionality in a general context. Or to play with alternative implementations ...

As usual you can test it from my own [repository](https://github.com/wllacer/archinstall.git) branch **flexible-menu2**;
or better yet, using this PR as a local branch via the commands (those strings between <> are names you can/should update to your need)

```
git remote add <upstream> git://github.com/archlinux/archinstall.git
git fetch <upstream> pull/916/head:<BRANCH_NAME>

```
*Updated 3/2: data_store argument has now to be explicit

### CODE REVIEW

**Comment by wllacer** [comment]
I have changed a bit the definition of the exec_func at Selector. Now it has two parameters: selector_name and result.
OTOH i've slighty changed the order of exection of individual components (at GeneralMenu.exec_option):
* first the pre_callback
* Then the selection function
* Then the exec function and
* Then the post_callback
* Finally, the check if the loop has to be ended

**Comment by Torxed** [comment]
Ready to merge it seams, but this functionality is undefined: https://github.com/archlinux/archinstall/blob/276b4bc83a45056d6a8760b14fe02cfeda22a543/archinstall/lib/user_interaction.py#L350

**Comment by dylanmtaylor** [comment]
> Ready to merge it seams, but this functionality is undefined:
> 
> https://github.com/archlinux/archinstall/blob/276b4bc83a45056d6a8760b14fe02cfeda22a543/archinstall/lib/user_interaction.py#L350

Is the undefined function called anywhere?

**Comment by wllacer** [comment]
It's a strange thing. In the last few days (after succesive mergers from master) the code in this branch has popped between needing `ask_for_a_timezone` and `ask_timezone`. I tried yesterday to fix it. But today's master returned to the opposite version (¿?), so the undefined function.
I'm also guilty of it, but even within master, we should be more careful with function name changing/deletion ...
When flake8 gives up complaining, i hope this is solved and stays stable

**Comment by wllacer** [comment]
> Ready to merge it seams, but this functionality is undefined:
> 
> https://github.com/archlinux/archinstall/blob/276b4bc83a45056d6a8760b14fe02cfeda22a543/archinstall/lib/user_interaction.py#L350

It's strange that it's me advising caution with the merge. I believe it works at least as good as the actual version. And I do love my "swiss" army knife script. But i can't get the feeling that it is still some way experimental.

**Comment by Torxed** [comment]
I think it was called `ask_timezone` from the time it was created but calling it we used `ask_for_a_timezone`.
I think this is just a mistake on my part when I tried to merge some 400+ lines of conflicts due to translations and stuff. And we actually have a duplicate definition that we can simply remove this erroneous one: https://github.com/archlinux/archinstall/blob/276b4bc83a45056d6a8760b14fe02cfeda22a543/archinstall/lib/user_interaction.py#L335-L350

**Comment by Torxed** [comment]
I'm resolving the merge conflicts and pulling this in to master. We might have to re-visit the files added in /examples as they should serve as small examples (aside from guided) preferably.

**Comment by wllacer** [comment]
> I'm resolving the merge conflicts and pulling this in to master. We might have to re-visit the files added in /examples as they should serve as small examples (aside from guided) preferably.

IIRC there is only a file at examples i've added. It's *swiss.py*. It fits the category. It shows a couple of diferent menús, and a couple of way to handle them in the workflows. It can be useful, too

**Comment by Torxed** [comment]
Both `only_hdd` and `swiss.py` have been added.
`only_hdd` is nice tho, but we need to clean it up a bit. But the concepts are nice.

I've merged the latest master, and in the future I think i want the following examples:
 * guided - the whole shabang
 * hdd - perform disk operations only
 * packages/installation - manage an installation (add/remove packages, add boot loader etc) as standalone calls

Merging whenever I fixed flake8 : )

**Comment by Torxed** [comment]
I don't know how to fix the [_ is not defined](https://github.com/archlinux/archinstall/runs/5083028543?check_suite_focus=true) in only_hdd @svartkanin. So I'm merging this as it's outside of the "overall workflow" and I think it works anyway. Just that flake8 doesn't know what `_` is :)

**Comment by svartkanin** [comment]
@Torxed flake8 should know actually, I've added an entry to the config rhat defies _ as a built-in

**Comment by wllacer** [comment]
(about the error at only_hd) I thought i had it solved ... The code is somewhere inside the definition of the general class, but i don't know why it isn't triggered in this case
I hope to have spare time this afternoon to debug it. @svartkanin can rest about it (i hope).
swiss.py at masteris also giving me troubles. I'll have a look at it.
I'll explain also what this module is about when i have time. Guests today for lunch ...

**Pull request merged**
