### PR TITLE
WIP plugin support

### PR DESCRIPTION
**Pull request by advaithm**
🚨 PR Guidelines:

# Describe your PR
WIP Plugin support, currently we don't have a way for users to use plugins. this is still pretty wip 
# Testing
untested will probably break
Any new feature or stability improvement should be tested if possible.
Please follow the test instructions at the bottom of the README or use the ISO built on each PR.

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
Can you make an example plugin as a test and demonstrate how this would be used?

**Comment by dylanmtaylor** [comment]
Probably needs a lot of doc updates before it goes in as well.

**Comment by advaithm** [comment]
yeah this is very wip, not sure if it even works

**Comment by Torxed** [comment]
> yeah this is very wip, not sure if it even works

That's the spirit! :D

**Comment by advaithm** [comment]
this is better implemented in  #393

**Pull request closed without merging**
