### PR TITLE
l10n/po: update Tamil translation

### PR DESCRIPTION
**Pull request by kbdharun**
## PR Description:

This PR updates the Tamil translation with updated translations (for modified/added strings)  and minor fixes to existing strings.

## Tests and Checks
- [ ] I have tested the code!<br>

### CODE REVIEW

**Review by kbdharun — COMMENTED** [review]
I was confused why the Time syncronization not completing string was repeating here but not shown in my side of Interface.

Seems like it is present twice in the POT file too.

image

https://github.com/archlinux/archinstall/blob/c3c175047e7feebddba6a68834aa33f6cdecb3c9/archinstall/locales/base.pot#L1246-L1266

**Comment by Torxed** [comment]
Not sure why that would be. Maybe it's poedit making a fuzz because it's been split into multiple lines in `base.po` upstream: https://github.com/archlinux/archinstall/blob/fef9269d38335908199e4b94cb3e0252dc504d9c/archinstall/locales/base.pot#L1246-L1248

You can do a `git pull origin master` (or use the web ui https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) into your master to see if the behavior disappear.

**Comment by kbdharun** [comment]
> You can do a git pull origin master (or use the web ui https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) into your master to see if the behavior disappear.

Hi, my branch is already synced with the master branch, the string repeats twice in the upstream POT file (`base.pot`). Should I remove the second one? (I linked this code line as a permalink in the previous comment for your reference earlier today)

**Comment by Torxed** [comment]
> the string repeats twice in the upstream POT file

I linked to the upstream .po file, and I could not find a duplicate.
Mind linking to the duplicate string?

**Comment by kbdharun** [comment]
> > the string repeats twice in the upstream POT file
> 
> I linked to the upstream .po file, and I could not find a duplicate. Mind linking to the duplicate string?

Sure, the string is present in lines 1246-1249 (A) and also repeated in 1263-1266 lines (B).

A:

https://github.com/archlinux/archinstall/blob/fef9269d38335908199e4b94cb3e0252dc504d9c/archinstall/locales/base.pot#L1246-L1249

B:

https://github.com/archlinux/archinstall/blob/fef9269d38335908199e4b94cb3e0252dc504d9c/archinstall/locales/base.pot#L1263-L1266

**Comment by Torxed** [comment]
Aah, because one is misspelled :see_no_evil: 
We should for sure just use correct spelling ^^

> Time syncronization
> Time synchronization

**Review by Torxed — APPROVED** [review]

**Pull request merged**
