### PR TITLE
Btrfs II

### PR DESCRIPTION
**Pull request by wllacer**
For master:
This is the second installement of the btrfs patches, with something more general, complementing PR #787 
Features:
1) For all filesystem types, we have created two new keys in the layout. Former options are mantained for backward compatibility. (see issue #835)
```json
{
    "/dev/loop0": {
        "partitions": [
            {
                ...
                "encrypted": false,
                "filesystem": {
                    "format": "btrfs",
                    "format_options":[                   for options to be used during the formatting of the fs (mkfs)
                        "--label liquindoy"
                    ],
                    "mount_options":[                  for options to be used at the mount of the partition/subvolume (mount)
                       "noatime",
                        "compress=lzo"
                    ]
                },
                "format": true,
                "mountpoint": null,
            }
        ],
        "wipe": true
    }
}
```
2) Now **btrfs** partitions (and subvolumes) can be encrypted and managed like any other filesystem via passwords and key files for not root partitions. Naturally we respect the upstream limitation than on **btrfs**, encryption is for full partitions (all the subvolumes inside, without exception)

3)  In **btrfs**, a certain level of compression (*zstd*) can be defined on the subvolume level, and more sophisticated modes at the partition level, we now allow both levels of definition, only that on the subvolume level, instead of being defined at mount point, it is handled via extended attributes.

# Testing
Till it is merged, you can test it at  my branch `https://github.com/wllacer/archinstall/tree/btrfs-encrypt`
Remember there is a script **only-hd** which only handles partitioning and mounting, not proceeding with the real arch installation.

# Limitations
There is still no UI. All use has to be via disk layout files

### CODE REVIEW

**Comment by wllacer** [comment]
A few technical details.
Most of the processing was streamlined when we discovered that we could subtitute the luks generated Partition object (unlocked device) for the normal Partition object at the directory entry partition['device_instance']. This way no special processing was needed during the mount phase for encrypted  partitions / subvolume mountpoints and their counterparts in the clear. It also allowed for some simplification of the manage_btrfs_subvolumes function.

This led to a total overhaul of Installer.mount_ordered_partition. Now this method is based on four loops thru a list of partitions dictionaries.:
* The first one open the encrypted partitions and creates a list of those which need the creation of a keyfile. As the creation of the object is instanced with *auto_unmount= false*, they are kept open as long as we need them
* The second one selects the btrfs partitions, creates the subvolumes and adds the new "partition dictionaries" needed for all the subvolumes which will be mounted
*  The third one selects all the entries which will be mounted and does the mounting. There is where we have put the support for mount options. Btw. it solves again issue #813, but with some different coding style as the solution from @Torxed two days ago (we use no more the old mountpoints dictionary).
* The forth and last is only for the unlocked devices which need the creation of keyfiles. Putting it at the end avoids some errors if the keyfile was created before the / directory had been mounted (not depending on the UI, but only from user written json files has this drawback)
One of the advantages we see with this approach is that it allows easy extensions in case other filesystems behave as divergent of the age old standard as **btrfs**
I like the code, but will accept that perhaps i overplayed a bit the use of list comprehensions here

**Comment by wllacer** [comment]
A full example of a disk layout file for btrfs without encryption
```json
{
    "/dev/loop0": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "format": true,
                "mountpoint": "/boot",
                "size": "513MiB",
                "start": "5MiB",
                "type": "primary"
            },
            {
                "btrfs": {
                    "subvolumes": {
                        "root": "/",
                        "home":{
                            "mountpoint":"/home",
                            "options":["compress"]
                        },
                        "var": {
                            "mountpoint":"/var",
                            "options":["nodatacow"]
                        },
                        "var/cache/pacman":null,
                        "var/lib/pacman": null,
                        ".snapshots": null
                    }
                },
                "encrypted": false,
                "filesystem": {
                    "format": "btrfs",
                    "format_options":[
                        "--label liquindoy"
                    ],
                    "mount_options":[
                        "noatime",
                        "compress=lzo"
                    ]
                },
                "format": true,
                "mountpoint": null,
                "size": "100%",
                "start": "518MiB",
                "type": "primary"
            }
        ],
        "wipe": true
    }
}
```
And another one with encryption (and two partitions)
```json
{
    "/dev/loop0": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "format": true,
                "mountpoint": "/boot",
                "size": "513MiB",
                "start": "5MiB",
                "type": "primary"
            },
            {
                "btrfs": {
                    "subvolumes": {
                        "root": "/",
                        "var": {
                            "mountpoint": "/var",
                            "options": [
                                "space_cache=v2",
                                "nodatacow"
                            ]
                        }
                    }
                },
                "encrypted": true,
                "filesystem": {
                    "format": "btrfs"
                },
                "format": true,
                "generate-encryption-key-file": true,            this partition includes the / mountpoint. key file will NOT be generated
                "mountpoint": null,
                "size": "4092MiB",
                "start": "518MiB",
                "type": "primary"
            },
            {
                "btrfs": {
                    "subvolumes": {
                        "home": {
                            "mountpoint": "/home",
                            "options": [
                                "space_cache=v2",
                                "compress",
                                "noatime"
                            ]
                        },
                        "opt": {
                            "mountpoint": "/opt",
                            "options": [
                                "space_cache=v2",
                                "noatime"
                            ]
                        },
                        "srv": {
                            "mountpoint": "/srv",
                            "options": [
                                "space_cache=v2",
                                "noatime"
                            ]
                        }
                    }
                },
                "encrypted": true,
                "filesystem": {
                    "format": "btrfs"
                },
                "format": true,
                "generate-encryption-key-file": true,
                "mountpoint": null,
                "size": "100%",
                "start": "4610MiB",
                "type": "primary"
            }
        ],
        "wipe": true
    }
}
```

**Comment by Torxed** [comment]
This is some solid work to improve the life of the btrfs handling!

**Comment by wllacer** [comment]
Having a look at my own "to-do" list, i recalled that there is an aditional bootloader option not in the general execution called **efistub**.  Most probably it needs some "btrfs care". My question is which priority this point could has for Archinstall as a project?

**Comment by Torxed** [comment]
> Having a look at my own "to-do" list, i recalled that there is an aditional bootloader option not in the general execution called **efistub**. Most probably it needs some "btrfs care". My question is which priority this point has for Archinstall as a project?

Very little as of now. It's hidden behind `--advanced` or through careful manuall addition in the JSON syntax.
More info can be found here #716. So you can safely ignore that for now, as users using it will be aware of any shortcomings.

**Comment by wllacer** [comment]
> > Having a look at my own "to-do" list, i recalled that there is an aditional bootloader option not in the general execution called **efistub**. Most probably it needs some "btrfs care". My question is which priority this point has for Archinstall as a project?
> 
> Very little as of now. It's hidden behind `--advanced` or through careful manuall addition in the JSON syntax. More info can be found here #716. So you can safely ignore that for now, as users using it will be aware of any shortcomings.
Thanks for the input
For what i've read in the arch wiki, and seen in the code, changes seem to be pretty trivial, (I'd say, copy the ones i did for systemd-bootctl); but the testing might not be. S,  implementing it will not be forgotten, but put on "low prio"

**Comment by Torxed** [comment]
Great work on this whole btrfs fixes.
I'll run some tests against master as a whole. Nothing appears to break but even if it does we have plenty of time to fix things before `v2.4.0` : ) So merging!

**Pull request merged**
