### PR TITLE
Implement Sway and use SDDM as Greeter

### PR DESCRIPTION
**Pull request by dylanmtaylor**
VirtualBox_ArchLinux_08_04_2021_15_05_28
VirtualBox_ArchLinux_08_04_2021_15_06_03

🚨 PR Guidelines:

# New features *(v2.2.0)*

Merge new features in to `torxed-v2.2.0`.<br>
This branch is designated for potential breaking changes, added complexity and new functionality.

# Bug fixes *(v2.1.4)*

Merge against `master` for bug fixes and anything that improves stability and quality of life.<br>
This excludes:
 * New functionality
 * Added complexity
 * Breaking changes

Any changes to `master` automatically gets pulled in to `torxed-v2.2.0` to avoid merge hell.

# Describe your PR

If the changes has been discussed in an Issue, please tag it so we can backtrace from the Issue later on.<br>
If the PR is larger than ~20 lines, please describe it here unless described in an issue.

# Testing

Any new feature or stability improvement should be tested if possible.
Please follow the test instructions at the bottom of the README.

*These PR guidelines will change after 2021-05-01, which is when `v2.1.4` gets onto the new ISO*

### CODE REVIEW

**Comment by advaithm** [comment]
I don't think we should use any greeter for sway. officially sway does not support any display managers https://github.com/swaywm/sway/pull/3634#issuecomment-462779163

**Comment by dylanmtaylor** [comment]
> I don't think we should use any greeter for sway. officially sway does not support any display managers [swaywm/sway#3634 (comment)](https://github.com/swaywm/sway/pull/3634#issuecomment-462779163)

It seems to work and might confuse users if they're booted to a system with no graphical login prompt. If we run into issues we can pull it out though

**Comment by advaithm** [comment]
We have a postinstall hook to tell the user to run `sway` to start it

**Comment by advaithm** [comment]
We also should raise a hard incompatibility error if a person uses the proprietary nvidia drivers since sway cannot run with the proprietary drivers

**Comment by dylanmtaylor** [comment]
> We also should raise a hard incompatibility error if a person uses the proprietary nvidia drivers since sway cannot run with the proprietary drivers

You won't get this case right now - since there is no reliance on Xorg this profile doesn't let you pick a driver. Nvidia works with noveau so we could install that instead for sway.

**Comment by advaithm** [comment]
Dude you literally can't run sway with the proprietary drivers. It has no idea how to use nvidia drivers. Also sway is wayland only. Sddm pulls xorg.

**Comment by Torxed** [comment]
> We have a postinstall hook to tell the user to run `sway` to start it

I think that we could add a sway specific option to the sway profile that aks:
```
Would you like to autostart sway on login [Y/n]: 
```
And have the installer set up one of the two supported methods mentioned in [Sway#Starting *(arch wiki)*](https://wiki.archlinux.org/index.php/Sway#Starting)

**Comment by advaithm** [comment]
sure

**Pull request merged**
