### PR TITLE
Improve Spanish translations

### PR DESCRIPTION
**Pull request by RotaN8**
## PR Description:

I have not reviewed all the translations but almost all, and I completed a few of them that were not defined

## Tests and Checks
- [ ] I have tested the code!<br>

I have not idea of how to test the translations, i don't think it needs a huge testing. And I don't have time to generate the ISO and to test it right now. Feel free to test yourself or cancel the pull request!

### CODE REVIEW

**Comment by Torxed** [comment]
Awesome work, could you run the translation script one more time so it updates the binary translation file as well?

**Comment by RotaN8** [comment]
@Torxed I'm very new to git/GitHub lol, did I get it right? If not, explain to me and I'll fix it!

Thank you!

**Comment by Torxed** [comment]
Apologies for my late response, I'll have to do some git magic but overall it looks ok :)

**Comment by kbdharun** [comment]
> Apologies for my late response, I'll have to do some git magic but overall it looks ok :)

As mentioned here https://github.com/archlinux/archinstall/pull/1750#issuecomment-1547268449, I would suggest you mark this PR as a draft as it will conflict with other translation PRs, once other PRs are merged in the mentioned comment. You can rebase this with the master and merge it.

**Comment by Torxed** [comment]
I'll close this one, as even with a rebase it causes a lot of weird merge conflicts and issues. Feel free to open a new PR where only the translated `.po` file is added with `git add archinstall/locales/<lang>/LC_MESSAGES/base.po`.

**Pull request closed without merging**
