### PR TITLE
DOCS: How to test a commit from a live image

### PR DESCRIPTION
**Pull request by dylanmtaylor**
# Pull Request Template

Make sure you've checked out the [contribution guideline](https://github.com/archlinux/archinstall/blob/master/CONTRIBUTING.md).<br>
Most of the guidelines are not enforced, but is heavily encouraged.

## Description

Please include a summary of the change and which issue is fixed.<br>
It is also helpful to add links to online documentation or to the implementation of the code you are changing.

## Bugs and Issues

If this pull-request fixes an issue or a bug, please mention the issues with the approriate issue referece *(Example: &#35;8)*.

## How Has This Been Tested?

If possible, mention any tests you have made with the current code base included in the pull-requests.<br>
Any core-developer will also run tests, but this helps speed things up. Below is a template that can be used:

As an example:

**Test Configuration**:
* Hardware: VirtualBox 6.1
* Specific steps: Ran installer with additional packages `nano` and `wget`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code to the best of my abilities
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation where possible/if applicable

### CODE REVIEW

**Comment by Torxed** [comment]
Can you actually run `pip uninstall archinstall` when the package is installed with pacman?

**Comment by dylanmtaylor** [comment]
> Can you actually run `pip uninstall archinstall` when the package is installed with pacman?

Not only can you do that, it actually works and I was able to boot into a working system afterwards.

**Comment by dylanmtaylor** [comment]
python-pip seems to be needed for the build/install stage anyways.

**Comment by dylanmtaylor** [comment]
So admittedly the package management with pip isn't best practice on an installed system, but it's not like what you do in live media matters much as this package isn't installed to the chrooted system.

**Comment by dylanmtaylor** [comment]
> Can you actually run `pip uninstall archinstall` when the package is installed with pacman?

I changed it to use pacman -R since that's likely more 'proper' on an Arch system.

**Comment by dylanmtaylor** [comment]
So I tried pacman -R archinstall and did the steps that way, but it gave me the old profiles still. I then did the pip uninstall archinstall and rebuilt and installed it and it showed the new ones and the unified kde *shrug*

**Comment by dylanmtaylor** [comment]
> Adjusted the layout based on your wording into a step by step structure.
> Is `python setup.py build` strictly nessecary? Or will that be taken care of by `install` as well?
> 
> Changed back to `pacman -R`

That is a great question. I don't know if install calls build, I guess I can try it and see.

**Comment by dylanmtaylor** [comment]
The build can be simplified by just running install, you are right. I'll change that.

**Pull request merged**
