### PR TITLE
updated deps added renovate

### PR DESCRIPTION
**Pull request by akac97**
Updated deps added renovate bot

### CODE REVIEW

**Comment by Torxed** [comment]
Never played around with renovatebot, thoughts from other contributors?
In general I'm a bit hesitant to tools that poke around too much, but perhaps this is fine? breakage concerns if versions are bumped?

**Comment by svartkanin** [comment]
@Torxed we use renovate bot at our company so I can vouch for it. It's quite neat, it will simply scan the dependency modules we have (which aren't a lot) and then raise a PR to update the dependency to the latest version. This means that we won't fall behind on dependencies management. 

Looking at their page though https://github.com/renovatebot/tutorial, it seems we need a bit more setup to get it running

**Comment by svartkanin** [comment]
That should be visible quite easily as the builds should fail. 
From what I could see there needs to be an app installed on the repo level

**Comment by Torxed** [comment]
Ah yea, it needs a runner that checks continuously I suppose.
That's not something I can setup I'm afraid.

**Comment by svartkanin** [comment]
@Torxed so is this a no-go or do we have to reach out to someone for it?

**Comment by Torxed** [comment]
I've asked the devops to look in to it :)

**Comment by klausenbusk** [comment]
Please checkout https://github.com/archlinux/archinstall/pull/2086.

**Comment by Torxed** [comment]
I assume this means devops is working hard on it :D

**Comment by Torxed** [comment]
With #2086, do we need this PR too?
If so, can we plug in the latest changes in `master`?

**Comment by svartkanin** [comment]
The actions have all been update to v4 already, so I think everything from this PR is already in master

**Pull request closed without merging**
