### PR TITLE
Fix 1538

### LINKED ISSUE #1538: Mounting disk issue during install - 2022.10.01
Hi, I've installed Arch on a few machines with no issues at all, but this time it's not having it... the following is from the CLI output.

Any help is greatly appreciated :-) Tried the usual, and nothing is mounted when I start. Even tried after a secure erase of the NVMe drive.

Same happens with ext4, and without encryption (on both file systems).

```
Press Enter to continue.
 ! Formatting [BlockDevice(/dev/nvme0n1, size=476.9GB, free_space=512GB, bus_type=nvme)] in 5....4....3....2....1....
Creating a new partition label on /dev/nvme0n1
Adding partition to BlockDevice(/dev/nvme0n1, size=476.9GB, free_space=512GB, bus_type=nvme), 1MiB->512MiB
Formatting /dev/nvme0n1p1 -> vfat
/usr/bin/mkfs.vfat -F32 /dev/nvme0n1p1
Marking partition Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=8dbabb2c-7bfd-4c15-ad40-4ed55ac308eb, fs=vfat) as bootable.
Setting boot on on (parted) partition index 1
Adding partition to BlockDevice(/dev/nvme0n1, size=476.9GB, free_space=512GB, bus_type=nvme), 513MiB->100%
Encrypting Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=8dbabb2c-7bfd-4c15-ad40-4ed55ac308eb, fs=vfat) (This might take a while)
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Formatting /dev/mapper/ainstnvme0n1p1 -> btrfs
Mounting BTRFSPartition(path=/dev/mapper/ainstnvme0n1p1, size=0.5, PARTUUID=None, parent=/dev/nvme0n1p1, fs=btrfs) to /mnt/archinstall/
Setting up subvolumes: [Subvolume(name='@', mountpoint='/', compress=False, nodatacow=False), Subvolume(name='@home', mountpoint='/home', compress=False, nodatacow=False), Subvolume(name='@log', mountpoint='/var/log', compress=False, nodatacow=False), Subvolume(name='@pkg', mountpoint='/var/cache/pacman/pkg', compress=False, nodatacow=False), Subvolume(name='@.snapshots', mountpoint='/.snapshots', compress=False, nodatacow=False)]
Mounting /boot to /mnt/archinstall/boot using Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=8dbabb2c-7bfd-4c15-ad40-4ed55ac308eb, fs=vfat)
Using mount order: [('/', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7ff210777910>), ('/.snapshots', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7ff210777a30>), ('/boot', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7ff2107776d0>), ('/home', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7ff210777760>), ('/var/cache/pacman/pkg', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7ff2107777f0>), ('/var/log', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7ff210777640>)]
Mounting subvolume @ on BTRFSPartition(path=/dev/mapper/ainstnvme0n1p1, size=0.5, PARTUUID=None, parent=/dev/nvme0n1p1, fs=btrfs) to /mnt/archinstall
Mounting subvolume @.snapshots on BTRFSPartition(path=/dev/mapper/ainstnvme0n1p1, size=0.5, PARTUUID=None, parent=/dev/nvme0n1p1, fs=btrfs) to /mnt/archinstall/.snapshots
Mounting Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=8dbabb2c-7bfd-4c15-ad40-4ed55ac308eb, fs=vfat) to /mnt/archinstall/boot
['/usr/bin/mount', '-t', 'vfat', '/dev/nvme0n1p1', '/mnt/archinstall/boot'] exited with abnormal exit code [8192]: b'mount: /mnt/archinstall/boot: /dev/nvme0n1p1 already mounted or mount point busy.\r\n       dmesg(1) may have more information after failed mount system call.\r\n'
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 311, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 316, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 141, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 160, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 145, in perform_installation
    installation.mount_ordered_layout(archinstall.arguments['disk_layouts'])
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 303, in mount_ordered_layout
    frozen_func()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 297, in <lambda>
    mount_queue[mountpoint] = lambda instance=partition['device_instance'], target=f"{self.target}{mountpoint}": instance.mount(target)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 569, in mount
    raise err
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 563, in mount
    mnt_handle = SysCommand(f"/usr/bin/mount -t {fs_type} {device_path} {target}")
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 435, in __init__
    self.create_session()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 486, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 275, in __exit__
    raise SysCallError(f"{self.cmd} exited with abnormal exit code [{self.exit_code}]: {self._trace_log[-500:]}", self.exit_code, worker=self)
archinstall.lib.exceptions.SysCallError: ['/usr/bin/mount', '-t', 'vfat', '/dev/nvme0n1p1', '/mnt/archinstall/boot'] exited with abnormal exit code [8192]: b'mount: /mnt/archinstall/boot: /dev/nvme0n1p1 already mounted or mount point busy.\r\n       dmesg(1) may have more information after failed mount system call.\r\n'
archinstall --config=./settings/user_configuration.json    196.52s user 6.13s system 150% cpu 2:14.30 total
1 root@archiso ~ #  
```

After the attempt:

```
1 root@archiso ~ # lsblk
NAME               MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
loop0                7:0    0 686.9M  1 loop  /run/archiso/airootfs
sda                  8:0    1  29.9G  0 disk  
├─sda1               8:1    1   783M  0 part  /run/archiso/bootmnt
└─sda2               8:2    1    15M  0 part  
nvme0n1            259:0    0 476.9G  0 disk  
├─nvme0n1p1        259:3    0   511M  0 part  
│ └─ainstnvme0n1p1 254:0    0   495M  0 crypt /mnt/archinstall/.snapshots
│                                             /mnt/archinstall
└─nvme0n1p2        259:4    0 476.4G  0 part  
root@archiso ~ # 
```

### PR DESCRIPTION
**Pull request by svartkanin**
According to the comments in the thread, this potentially fixes #1538

### CODE REVIEW

**Comment by gabrc52** [comment]
I just manually copied the 2 changed files into a live arch and it says `ImportError: cannot import name 'encrypted_partitions' from partially initialized module 'archinstall.lib.disk' (most likely due to a circular import) (/usr/lib/python3.10/site-packages/archinstall/lib/disk/__init__.py)`. I'll try cloning/copying over the whole repo

**Comment by gabrc52** [comment]
signal-2022-12-24-161838_002

It doesn't seem to be successful for me. Sorry for the bad picture--I can send a better logfile if needed.

**Comment by Torxed** [comment]
screenshot

Not sure exactly why, I can debug a bit more but I'll look through some other PR's before I go down the rabbit hole :)

**Comment by svartkanin** [comment]
It's okay, I'll close this for now as the rewrite should fix it

**Comment by svartkanin** [comment]
Has been merged into https://github.com/archlinux/archinstall/pull/1604 and will be added with it

**Pull request closed without merging**
