### PR TITLE
Add minimal profile and implement idea of 'top-level' profiles

### PR DESCRIPTION
**Pull request by dylanmtaylor**
This will allow for a much cleaner install (minimal) if desired and can be used to move driver and audio server selection so they're only done on a desktop installation type. This closes issue #210

# Pull Request Template

Make sure you've checked out the [contribution guideline](https://github.com/archlinux/archinstall/blob/master/CONTRIBUTING.md).<br>
Most of the guidelines are not enforced, but is heavily encouraged.

## Description

Please include a summary of the change and which issue is fixed.<br>
It is also helpful to add links to online documentation or to the implementation of the code you are changing.

## Bugs and Issues

If this pull-request fixes an issue or a bug, please mention the issues with the approriate issue referece *(Example: &#35;8)*.

## How Has This Been Tested?

If possible, mention any tests you have made with the current code base included in the pull-requests.<br>
Any core-developer will also run tests, but this helps speed things up. Below is a template that can be used:

As an example:

**Test Configuration**:
* Hardware: VirtualBox 6.1
* Specific steps: Ran installer with additional packages `nano` and `wget`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code to the best of my abilities
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation where possible/if applicable

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
I'm planning on making this work with the changes in #208

**Comment by dylanmtaylor** [comment]
I think I can do the filtering with 

archinstall.arguments['profile'] = archinstall.select_profile(filter(lambda top_level_profiles: (profile.is_top_level_profile), archinstall.list_profiles())

in line 170 of guided.py; going to test that now before committing.

**Comment by dylanmtaylor** [comment]
This commit is functional and works as expected, perhaps someone has feedback on a cleaner way to implement this though.

Screenshot of what it looks like in the installer:

VirtualBox_ArchLinux_07_04_2021_09_18_39

**Comment by dylanmtaylor** [comment]
Just added the i3 profiles to the desktop top-level profile, so the screenshot is a little dated - these are now selectable. This PR is ready for review :)

**Comment by dylanmtaylor** [comment]
Just gave this a test run - the minimal profile is tested and working; selecting desktop gets you a list of desktop environments, haven't tested them all but GNOME works as expected (suffers from the fstab newline bug though which is not in this branch). @Torxed do you think this is good to go in? Happy to make adjustments if needed.

**Comment by dylanmtaylor** [comment]
This is what a minimal install looks like after reboot:

VirtualBox_ArchLinux_07_04_2021_12_13_04

It's fully functional. I had to redo the newline patch to get the installer working without editing the files after pulling this branch, but it works now, if anyone wants to test this.

**Comment by Torxed** [comment]
Merged: With the reminder of what I mentioned in a discussion:
> Archinstall supports this already:
> ```
> python -m archinstall minimal
> ```
> It sources the examples/minimal.py and I was thinking of updating that to be a very minimal installation.
But the overall concept should make filtering profiles a bit easier! Well done!

**Pull request merged**
