### PR TITLE
Spanish translation file

### PR DESCRIPTION
**Pull request by erickisos**
# Describe your PR

This is just the spanish translation for the archinstaller

Relates to: #893

### CODE REVIEW

**Comment by svartkanin** [comment]
@erickisos I just raised an update for the nationalization https://github.com/archlinux/archinstall/pull/944, it's fixing some odd texts and adds some previously missed translations. 
I would like to update your PR with my changes so we can get the latest clean version translated into spanish if that's okay with you? 
It shouldn't cause any major issues, but some few texts might have to be retranslated

**Comment by svartkanin** [comment]
I just realized that I don't have any mighty power and can't push anything to this PR/branch but I'd like to help to resolve the updated texts if you like

**Comment by erickisos** [comment]
It would be great! But I don't know how can I give you permissions to do that, let me check

**Comment by dylanmtaylor** [comment]
> I just realized that I don't have any mighty power and can't push anything to this PR/branch but I'd like to help to resolve the updated texts if you like

You can open a PR against his branch in his fork.

**Comment by Torxed** [comment]
The easiest way is if @svartkanin forks your fork, and submits a patch to it, that you accept and then I accept this.

```
Upstream -> erickisos -> svartkanin
   PR <------- PR <----------|
```

**Comment by svartkanin** [comment]
Sounds good, I'll try to get that done today

**Comment by svartkanin** [comment]
@erickisos I raised a PR against your master that should include the changes

**Comment by Torxed** [comment]
Looks like this is ready to go in? :)

**Comment by erickisos** [comment]
Yessss, we are ready now!

**Comment by Torxed** [comment]
Thank you for this contribution! :D

**Pull request merged**
