### PR TITLE
Update ta locale

### PR DESCRIPTION
**Pull request by kbdharun**
- This fix issue: 

## PR Description:

- Updating ta locale, Adding 3 strings.

## Question:

- I noticed in PR #1467, that Tamil (ta locale) needs external dependencies. Can someone give me some insights on how to set up custom fonts so that I can try installing it and testing out the arch install?
## Tests and Checks
- [ ] I have tested the code!<br>
  
Signed-off-by: K.B.Dharun Krishna <kbdharunkrishna@gmail.com>

### CODE REVIEW

**Comment by Torxed** [comment]
Dang it, so @svartkanin wrote a beautiful guide on how to get it working..
But I can't for the life of me find it right now..

**Comment by svartkanin** [comment]
@kbdharun @Torxed it's in the Readme https://github.com/archlinux/archinstall/blob/master/archinstall/locales/README.md :)

**Comment by kbdharun** [comment]
> @kbdharun @Torxed it's in the Readme https://github.com/archlinux/archinstall/blob/master/archinstall/locales/README.md :)

Thanks for the reply. I noticed it on the page. My question is should I download a package like from Google font, etc  and place it in the aforementioned location. Would it work?

I will try to do it inside Arch.

Also, When performing a fresh installation from livecd. How can I download a font package and place it in the required location?

**Comment by Torxed** [comment]
> Also, When performing a fresh installation from livecd. How can I download a font package and place it in the required location?

`wget` would be your best friend here :)

> It would be nice if there is some documentation on how to use archinstall with a required font package for accessing it maybe in arch wiki or here.

I agree, and I'll try to get it into the wiki. Some of these features are very new so documentation is a bit behind. I apologize!

**Comment by Torxed** [comment]
Thank you for this addition! :)

**Pull request merged**
