### PR TITLE
Refactor `build_iso.sh` zprofile

### PR DESCRIPTION
**Pull request by codefiles**
Refactor `build_iso.sh` to use a here document and tee for creating and outputting the zprofile.

### CODE REVIEW

**Comment by Torxed** [comment]
Some bash dark arts here ^^ Looks good tho. I'm on my phone and can't merge the conflicts very well.

**Comment by codefiles** [comment]
I'll take care of the merge.

**Comment by Torxed** [comment]
Merged, swift work!

**Comment by codefiles** [comment]
Thanks. Fast on your part too. 😃

**Pull request merged**
