### PR TITLE
Better translation for Turkish

### PR DESCRIPTION
**Pull request by AlperShal**
Better translation for Turkish in the meaning of following source text, grammer (tense), vocabulary and meaning. Also left some linux/partitioning terminologies in English with translation given in parentheses so power-users or tutorial/documentation followers who decides to use setup in Turkish can also easily understand.

Edit: Also, I actually started 2 hours ago after other Turkish translation has been confirmed and I didn't know there was a pull request on going. I am submitting this without giving any credit to the other translator because I translated it all on my own. Maybe not really important for the description of the request but it is important for me. :)

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
To be perfectly honest, I don't know Turkish, so I have no idea which translation is better here. They do look vastly different though.

**Comment by AlperShal** [comment]
> To be perfectly honest, I don't know Turkish, so I have no idea which translation is better here. They do look vastly different though.

I also don't know how I can prove mine is better but for example;
Source
"Select a graphics driver or leave blank to install all open-source drivers"
Other Guy's
"Tüm açık kaynaklı sürücüleri yüklemek için bir grafik sürücüsü seçin veya boş bırakın"
Mine
"Bir grafik sürücüsü seç ya da tam açık-kaynak sürücüler için boş bırak"

That guy's translation means: "To install every open source drivers choose a graphics drive or leave it blank", you don't have to trust me: [Google Translate](https://translate.google.com/?sl=tr&tl=en&text=T%C3%BCm%20a%C3%A7%C4%B1k%20kaynakl%C4%B1%20s%C3%BCr%C3%BCc%C3%BCleri%20y%C3%BCklemek%20i%C3%A7in%20bir%20grafik%20s%C3%BCr%C3%BCc%C3%BCs%C3%BC%20se%C3%A7in%20veya%20bo%C5%9F%20b%C4%B1rak%C4%B1n&op=translate)
That's a critic mistake to do as you know as well for a translation. One I found right now.

**Comment by castillofrancodamian** [comment]
> 

Are you saying Google Translate is invalid? Because I use that tool to translate.

**Comment by wiseweb-works** [comment]
I reviewed AlperShal's (@AlperShal) new translation. He thinks his translation is better. I'm not against such things. For me, the benefit of the community is more important than the benefit of the person. Therefore, there is no problem on my part for you to approve the pull request he has opened. However, in the next few days if there are corrections to this translation from the community members, I suggest that he accept it with gently. Because both contextual translation and direct translation will be partially right and partially wrong to the users. Sometimes it is not possible to solve this problem completely, even in a text written in Turkish. That's all for now.

**Comment by dylanmtaylor** [comment]
> I reviewed AlperShal's (@AlperShal) new translation. He thinks his translation is better. I'm not against such things. For me, the benefit of the community is more important than the benefit of the person. Therefore, there is no problem on my part for you to approve the pull request he has opened. However, in the next few days if there are corrections to this translation from the community members, I suggest that he accept it with gently. Because both contextual translation and direct translation will be partially right and partially wrong to the users. Sometimes it is not possible to solve this problem completely, even in a text written in Turkish. That's all for now.

I think ultimately whatever individual translations are better and more useful for native speakers are the ones that should be used. It's almost impossible for a person who doesn't speak the language to review and decide which translation is better. I must admit that I'd have no idea even if a fake translation was submitted. So, it's a bit on the honor system. Between the two of you, can you try to come up with whatever is the best translation for the end users? Maybe discuss individual translations of strings. As I don't speak Turkish and I'm pretty sure that @Torxed doesn't as well, it's going to be hard to review for us.

**Comment by AlperShal** [comment]
We (@wiseweb-works and @AlperShal) both worked on the translation and resulted it with [my latest commit](https://github.com/archlinux/archinstall/pull/1238/commits/2ec5282b085b6d680b8484a1c18c642b8a914df4) on this pull request. You may wait for @wiseweb-works to confirm our work and then merge it. Thanks for being so helpful @wiseweb-works and @dylanmtaylor.

Also, about the question of @castillofrancodamian,
> Are you saying Google Translate is invalid? Because I use that tool to translate.
I think you used Google Translate for Spanish (your last pull request), since I don't really know about Spanish and didn't have any experience with the translation of Spanish with Google, I can't really say you can or can not trust Google for Spanish. But, because Turkic languages are VERY different from English and alikes. So when using such tools not always but by a pretty high chance we are having false results. It is always better to translate languages you know and not depend on auto-translators.

**Comment by dylanmtaylor** [comment]
My vote is to merge this one, @Torxed

**Comment by castillofrancodamian** [comment]
> We (@wiseweb-works and @AlperShal) both worked on the translation and resulted it with [my latest commit](https://github.com/archlinux/archinstall/pull/1238/commits/2ec5282b085b6d680b8484a1c18c642b8a914df4) on this pull request. You may wait for @wiseweb-works to confirm our work and then merge it. Thanks for being so helpful @wiseweb-works and @dylanmtaylor.
> 
> Also, about the question of @castillofrancodamian,
> 
> > Are you saying Google Translate is invalid? Because I use that tool to translate.
> 
> I think you used Google Translate for Spanish (your last pull request), since I don't really know about Spanish and didn't have any experience with the translation of Spanish with Google, I can't really say you can or can not trust Google for Spanish. But, Turkic languages are VERY different from English and alikes. So when using such tools not always but by a pretty high chance we are having false results. It is always better to translate languages you know and not depend on auto-translators.

Sure. I translated in Spanish because it is my natural language and I know if it makes a good translation or if I have to intervene, which is in most cases.

**Comment by Torxed** [comment]
Thank you for this work! And happy to see that you all worked together! Keep it up! :)

**Pull request merged**
