### PR TITLE
Updated Turkish translation

### PR DESCRIPTION
**Pull request by eren-ince**
- This fix issue: 

## Tests and Checks
- [ ] I have tested the code!<br>

### CODE REVIEW

**Comment by svartkanin** [comment]
Can you run the script again to generate the .mo file otherwise the translations want be in effect

**Comment by ernince** [comment]
> Can you run the script again to generate the .mo file otherwise the translations want be in effect

Done

**Comment by Torxed** [comment]
Thank you for this, I had to resolve a merge conflict. I hope I didn't butcher the language too hard when choosing which sentence should go in.

**Comment by eren-ince** [comment]
> Thank you for this, I had to resolve a merge conflict. I hope I didn't butcher the language too hard when choosing which sentence should go in.

It looks nice.

**Pull request merged**
