### PR TITLE
Implement Sway

### PR DESCRIPTION
**Pull request by dylanmtaylor**
Create sway.py files and use GDM as greeter since it supports the Sway desktop environment.

🚨 PR Guidelines:

# New features *(v2.2.0)*

Merge new features in to `torxed-v2.2.0`.<br>
This branch is designated for potential breaking changes, added complexity and new functionality.

# Bug fixes *(v2.1.4)*

Merge against `master` for bug fixes and anything that improves stability and quality of life.<br>
This excludes:
 * New functionality
 * Added complexity
 * Breaking changes

Any changes to `master` automatically gets pulled in to `torxed-v2.2.0` to avoid merge hell.

# Describe your PR

If the changes has been discussed in an Issue, please tag it so we can backtrace from the Issue later on.<br>
If the PR is larger than ~20 lines, please describe it here unless described in an issue.

# Testing

Any new feature or stability improvement should be tested if possible.
Please follow the test instructions at the bottom of the README.

*These PR guidelines will change after 2021-05-01, which is when `v2.1.4` gets onto the new ISO*

### CODE REVIEW

**Comment by Torxed** [comment]
If you want, we could merge this into master.
It doesn't strictly add complexity but improves quality of life for those that want this.

**Comment by dylanmtaylor** [comment]
> If you want, we could merge this into master.
> It doesn't strictly add complexity but improves quality of life for those that want this.
> 
> Other than that, looks good and I'm happy to merge!

I didn't pull the other DEs into master, so maybe we should cherry-pick in cinnamon.py and xfce4.py as well?

**Comment by dylanmtaylor** [comment]
So this *works* perfectly, but I'd like to test some more, it looks like it's pulling in some GNOME packages I don't want. You can use this and it boots to sway but I'm getting a lot more than just GDM here.

**Comment by dylanmtaylor** [comment]
Much better :)
VirtualBox_ArchLinux_08_04_2021_15_06_03
VirtualBox_ArchLinux_08_04_2021_15_05_28

**Comment by dylanmtaylor** [comment]
> If you want, we could merge this into master.
> It doesn't strictly add complexity but improves quality of life for those that want this.
> 
> Other than that, looks good and I'm happy to merge!

I will make the same request against master too.

**Comment by dylanmtaylor** [comment]
Going to redo against master with same work.

**Pull request closed without merging**
