### PR TITLE
Adding Hyperland wm

### PR DESCRIPTION
**Pull request by xeniumcode**
- The implementation of  issue: #1727 

## PR Description:
Adding Hyperland wm with its must have dependency's .

### CODE REVIEW

**Comment by Torxed** [comment]
Thank you for the contribution! :)

**Comment by Scotty-Trees** [comment]
I'm noticing **hyperland** and **hyprland** (the "E" is missing) are being using interchangeably, is that by choice or a mistake?

**Comment by vaxerski** [comment]
hyperland is a clothing brand. My wayland compositor is called hyprland, without an e.

**Comment by Torxed** [comment]
I noticed you found #1824 :)

**Pull request merged**
