### PR TITLE
Support for multiple network interfaces

### PR DESCRIPTION
**Pull request by svartkanin**
This addresses #1020. 

This will support the configuration of multiple network interfaces.
image

There are some breaking changes to the current version in master. For the configuration file, the interfaces can now be defined as

```
{
...
"nic": {
    "type": "manual", 
    "config": [
        {<interface configurations},
        {<interface configurations}
    ]
}
...
}
```

### CODE REVIEW

**Comment by Torxed** [comment]
I like this one, I'll merge it later today.

**Comment by wllacer** [comment]
@svartkanin . Yep. You're right, it ought to be self.data at the ListManager ... but it will break some code at PR #1053. Not that important (just a find/replace). Warn me when this is upstreamed, to make the changes

**Comment by svartkanin** [comment]
@wllacer yes I did some refactoring there i hope that's okay. I got a bit confused which attributes are private and which ones public. I also updated some callbacks to actually pass the data into it instead of accessing it via the attributes.
 The reason is that for me as a newvie using this new class it's very difficult to determine which variable stores what and I had to go through the code to know what I should access. However, if you override a function that gets everything relevant as an argument I can simply look at those and decide what to use :)

**Comment by svartkanin** [comment]
@Torxed Can we merge this if you're happy with the changes :)

**Comment by Torxed** [comment]
I'm always happy with the changes :D Merged!

**Pull request merged**
