### PR TITLE
Tighten up flake8 tests used by GitHub Action lint_python

### PR DESCRIPTION
**Pull request by cclauss**
🚨 PR Guidelines:

# New features *(v2.2.0)*

All future work towards *`v2.2.0`* is done against `master` now.<br>
Any patchwork to existing versions will have to create a new branch against the tagged versions.

# Describe your PR

If the changes have been discussed in an Issue, please tag it so that we can backtrace from the issue later on.<br>
If the PR is larger than ~20 lines, please describe it here unless described in an issue.

Tighten up flake8 tests used by lint_python GitHub Action

# Testing

Any new feature or stability improvement should be tested if possible. Please follow the test instructions at the bottom of the README or use the ISO built on each PR.

These are tests run by the lint_python GitHub Action.

### CODE REVIEW

**Comment by cclauss** [comment]
`psf/black` will autofix these kind of issues...
```
 1     E201 whitespace after '('
1     E202 whitespace before ')'
13    E226 missing whitespace around arithmetic operator
1     E252 missing whitespace around parameter equals
1     E262 inline comment should start with '# '
4     E265 block comment should start with '# '
12    E303 too many blank lines (2)
1     E305 expected 2 blank lines after class or function definition, found 1
1     E401 multiple imports on one line
```

**Comment by Torxed** [comment]
> [`psf/black`](https://github.com/psf/black) will autofix these kind of issues...
> 
> ```
> 1     E201 whitespace after '('
> 1     E202 whitespace before ')'
> 13    E226 missing whitespace around arithmetic operator
> 1     E252 missing whitespace around parameter equals
> 1     E262 inline comment should start with '# '
> 4     E265 block comment should start with '# '
> 12    E303 too many blank lines (2)
> 1     E305 expected 2 blank lines after class or function definition, found 1
> 1     E401 multiple imports on one line
> ```

Well aware, but black is too uncompromising :)

**Comment by Torxed** [comment]
There's just one final issue, and I can't see where the hell it gets it from.
```
./archinstall/lib/disk/blockdevice.py:5:1: F401 '.helpers.all_disks' imported but unused
from .helpers import all_disks
^
./archinstall/lib/disk/blockdevice.py:12:4: F811 redefinition of unused 'all_disks' from line 5
			from .helpers import all_disks
			^
1     F401 '.helpers.all_disks' imported but unused
1     F811 redefinition of unused 'all_disks' from line 5
2
Error: Process completed with exit code 1.
```

To me, the source of `./archinstall/lib/disk/blockdevice.py` has no duplicate imports: https://github.com/cclauss/archinstall/blob/2fcd8198b28744bad471b11d287a39ead267af67/archinstall/lib/disk/blockdevice.py#L5-L14

**Comment by cclauss** [comment]
I would put `# flake8: noqa` at the top of the file to force flake8 to ignore the entire file and land the PR.  Then I would go back and do a follow-up PR that removed the `# flake8: noqa` and debug the issue in isolation.

**Comment by Torxed** [comment]
Great work! And if nothing else, finally made me go through the code and fix all those star imports which I wasn't proud of.

**Comment by cclauss** [comment]
https://github.com/asmeurer/removestar

**Pull request merged**
