### PR TITLE
Modify "Española" to "Español"

### PR DESCRIPTION
**Pull request by victorbnl**
## PR Description:

So the translated name of Spanish is defined as "Española". It's pretty unnatural. At first, I thought it might be a shorthand for something like "la idioma española" : "the Spanish language", which, while still being really strange, would make a little bit of sense. Nevertheless, when looking at the other languages' names, they don't seem to follow this "convention" : French is "Français" and not "Française", Russian is "Ruskij" and not "Ruskaja"... 

## Tests and Checks
- [ ] I have tested the code!

### CODE REVIEW

**Comment by castillofrancodamian** [comment]
@victorbnl It will have been a mistake by the author who does not speak Spanish like us.

**Comment by victorbnl** [comment]
Yep that's what I came to think eventually

**Comment by castillofrancodamian** [comment]
@victorbnl What happened?

**Comment by victorbnl** [comment]
Well, I deleted my fork of the repository and I thought the pull request was going to stay open, as it used to on GitHub.

**Comment by victorbnl** [comment]
I think the PR is mergeable again now

**Comment by Torxed** [comment]
> @victorbnl It will have been a mistake by the author who does not speak Spanish like us.

It's more an issue of:
 * https://github.com/archlinux/archinstall/pull/1499
 * https://github.com/archlinux/archinstall/pull/1474

**Comment by Torxed** [comment]
Ignore my previous comment, I am a bit tired and thought the two PR's I linked added the `a`. It simply was a miss to not remove it from the translation file too. Merging!

**Pull request merged**
