### PR TITLE
Fix name of Hyperland to Hyprland

### PR DESCRIPTION
**Pull request by Jayanth-Parthsarathy**
- This fix issue: #2027 

## PR Description:
This is just a simple PR with name changes. I just fixed the typo in the profile name from **Hyperland** to **Hyprland**

- [x] I have tested the code!

### CODE REVIEW

**Comment by Jayanth-Parthsarathy** [comment]
I see now that even the file name and the class name are having the same typo. Waiting for reviewer to suggest whether to change these names too

**Review by lavafroth — CHANGES_REQUESTED** [review]
Yep, we'd rather have the file name, class names and packages coincide. It would be great if you rename the files, class names and any references to respective classes.

**Comment by lavafroth** [comment]
@Torxed note that #1999 attempts to fix the same naming issue.

**Comment by Jayanth-Parthsarathy** [comment]
As @lavafroth requested, I have changed the name of the file to hyprland.py and also changed the class name an the actual name.

**Comment by sausix** [comment]
#2022 is related too.

**Comment by Jayanth-Parthsarathy** [comment]
@sausix Seems like they have not changed the typo in the class name.

**Review by lavafroth — APPROVED** [review]
Great! We'll just @Torxed to review this and the other PRs before merging.

**Comment by Jayanth-Parthsarathy** [comment]
> Great! We'll just wait for @Torxed to review this and the other PRs before merging.

Sure, thank you for reviewing this pull request.

**Comment by Torxed** [comment]
Thank you for your patience.
We've worked out a better structure on merging now and I've got some additional help to offload responsabilities. So hopefully merging will be smoother going forward as I'm not the only one who can merge anymore :tada: :)

I'll have to have a look at all the PR's and compare diffs, as there's a few (including me being involved) in renaming it.

**Comment by svartkanin** [comment]
Thanks for the change, there were quite a few other PRs fixing this as well so we'll go ahead with https://github.com/archlinux/archinstall/pull/1824 as it fixes more things

**Pull request closed without merging**
