### PR TITLE
Rework network config

### PR DESCRIPTION
**Pull request by svartkanin**
Addresses #991

This is a rework of the network configuration. The new input structure, mainly relevant for the configuration files is 
```
"nic": {
    "type": <ISO|NM|MANUAL>,
    "iface": <str>,  # interface name
    "ip": <ip>,
    "dhcp": <boolean>,
    "gateway": <ip>,  #optional
    "dns": [<str>]  #optional
}
```

I've created a new container `NetworkConfiguration` to store the configuration data. This allows to group some functionality together and give guided.py and swiss.py a bit more air to breath. 

I've updated the documentation as well (hopefully I didn't miss anything). 

# Breaking changes
Existing custom configuration files will not work anymore with the new format and if any `nic` attribute is defined it will be ignored unless there are the new fields specified. 
The new configuration format for `nic` is expected to be in the following format 
```
"nic": {
    "type": <ISO|NM|MANUAL>, 
    "iface": <str>, 
    "dhcp": <boolean>,
    "ip": <ip>,
    "gateway": <ip>,  #optional
    "dns": [<str>]  #optional
}
```

- type: ISO -> Copy the current iso configuration, NM -> Setup and configure NetworkManager, MANUAL -> Use custom config
- iface: Interface to configure
- dhcp: If set to false  `auto DHCP` will be used otherwise `static IP`
- ip: Ip address, is mandatory if DHCP is false
- gateway: Optional gateway 
- dns: Optional list of DNS servers

### CODE REVIEW

**Comment by Torxed** [comment]
Great PR! And Thank you for summarizing the breaking changes.
I'll have a merge spree this weekend :) So hang tight!

**Comment by wllacer** [comment]
Maybe a bit too late, but couple of comments. I like the way you have solved it, but, could it be extended to a list/dict with several entries?. If a machine has ethernet and wifi, now you define explicitly either of them or are both left to NM to manage. There is no way to explicitly defined both (dual ethernet configurations are not that popular as they were, but would fall in the same category).

You seem to have done away with the conversion from the old to the new format at `load_config`. Am I right? Any technical reason behind? It's a matter of schools, but intentional compatibility breaks make me very nervous (especially if they seem relatively easy to brigde)

**Comment by svartkanin** [comment]
> Maybe a bit too late, but couple of comments. I like the way you have solved it, but, could it be extended to a list/dict with several entries?. If a machine has ethernet and wifi, now you define explicitly either of them or are both left to NM to manage. There is no way to explicitly defined both (dual ethernet configurations are not that popular as they were, but would fall in the same category).

That's a great point actually. I was mainly trying to keep the existing functionality but thinking about it I think it makes a lot of sense to be able to configure multiple ifaces.
With this there would be some significant changes though, we will have to rework how the network menu works to allow multiple configurations.

@Torxed @wllacer My proposal in that case is to allow 
"Copy..." as rhe single option and then as an alternative to configure multiple interfaces manually. Meaning that qe don't allow copy the current config and configuring an interface.
If it's okay I'd prefer to do that in a different PR though 

@wllacer My reasoning for removing the backwards compatibility was that it's not a major break, meaning that it won't break resulting in an error but simply take it as "no config provided". It would mean that we don't have to keep maintaining it. If you think it's worth it I'm happy to keep it in there :)
As an alternative, what about printing a message to inform that they're using an old incompatible network config and should switch to the new one?

**Comment by svartkanin** [comment]
> A thought, is it worth creating a config lifting tool? --convert-conf for instance?

Would that be to convert older to non backwards compatible configs?

**Comment by Torxed** [comment]
I'm happy with this as it is, and we can open separate PR's for the rest.

I was thinking the tool could read the old config format and convert it - making breaking changes smoother. Probably a lot of effort for this tho.

**Comment by svartkanin** [comment]
Sounds good, I'll pick up the extension as this is merged.

I think having a whole tool just for this change is a bit too much :) 

Shall we put in the backwards compatibility again or we're happy with the breaking changes?

**Comment by Torxed** [comment]
> Sounds good, I'll pick up the extension as this is merged.
> 
> I think having a whole tool just for this change is a bit too much :)
> 
> Shall we put in the backwards compatibility again or we're happy with the breaking changes?

Happy with it. We already have a lot of breaking changes, I'll announce it and see if I can come up with a technical solution to pipe old configs to the new layout transparently or something :)

**Comment by Torxed** [comment]
There were some parallel changes to `user_interaction.py`. I think I got it clean in, but poke me if something's wrong :)

**Pull request merged**
