### PR TITLE
Fix (some) mypy things

### PR DESCRIPTION
**Pull request by svartkanin**
An incredibly unspectacular PR to fix some of the mypy issues, I'll try to add more soon

### CODE REVIEW

**Comment by Torxed** [comment]
We should cross reference this with #846 : ) I guess I can merge this one after the flake8 issues are fixed and then merge those into my WIP PR.

**Comment by svartkanin** [comment]
Ahh cool didn't know there was an open issue for this

**Comment by svartkanin** [comment]
I see there's a mypy type checking running in the pipeline, I suspect that one is not actually stopping any mypy issues?

**Comment by Torxed** [comment]
the pipeline has `|| exit 0`: https://github.com/archlinux/archinstall/blob/4b3b21ed756463914d618abe11345c9839217473/.github/workflows/mypy.yaml#L16

which tells github that it "always exits nicely" until we got all the mypy issues sorted. its not a huge priority but would be nice :)

**Pull request merged**
