### PR TITLE
Updating Partition() information after mount and unmount.

### PR DESCRIPTION
**Pull request by Torxed**
- This fix issue: #1495 

## PR Description:

As described in the issue, we forgot to update partition information after `mount` and `umount` calls.
This leads `archinstall` to believe the partition isn't mounted anywhere.

This PR will:

1) Make sure the mount information (and general partition information) is updated after every `mount` or `umount` call
2) Add better error handling to `Partition().raw_parted` so that we can get better debug information out of it
3) Adds back `lsblk` information retrieval whenever `PartitionInfo()` is instantiated, making sure information such as `PARTUUID` and `UUID` is always fetched properly. If `PartitionInfo()` is instantiated too quickly after a `partprobe` there was no way for that information to be repopulated.

## Tests and Checks
- [x] I have tested the code!<br>

Tested with 2 disk layouts:
```json
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "btrfs": {
                    "subvolumes": [
                        {
                            "compress": false,
                            "mountpoint": "/",
                            "name": "@",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/home",
                            "name": "@home",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/var/log",
                            "name": "@log",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/var/cache/pacman/pkg",
                            "name": "@pkg",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/.snapshots",
                            "name": "@.snapshots",
                            "nodatacow": false
                        }
                    ]
                },
                "encrypted": true,
                "filesystem": {
                    "format": "btrfs",
                    "mount_options": [
                        "compress=zstd"
                    ]
                },
                "generate-encryption-key-file": true,
                "mountpoint": null,
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
```
```json
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "format": true,
                "mountpoint": "/boot",
                "size": "513MiB",
                "start": "1MiB",
                "type": "primary"
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "10GiB",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
```

Both work.

### CODE REVIEW

**Comment by Torxed** [comment]
Another issue is that the NVMe drives are really quick, so we'll end up here 5 times: https://github.com/archlinux/archinstall/blob/5c8eb7144d9583a8a117a4e892b1e78be1324a28/archinstall/lib/disk/filesystem.py#L271-L274

And then crash at: https://github.com/archlinux/archinstall/blob/5c8eb7144d9583a8a117a4e892b1e78be1324a28/archinstall/lib/disk/filesystem.py#L282-L285

Where the `New partitions:` will show:
```
New partitions: {None, 12312-512512-123123}
```
Indicating that the `Partition()` object never got it's information refreshed properly.

**Comment by Torxed** [comment]
So for my own sanity. The loop above, it re-creates all the `Partition()` objects on each loop.
So there's no need to call `Partition()._fetch_information()` additionally.

But why the `Partition.part_uuid` returns `None` is beyond me. Especially after 5 loops with 1, 2, 3 and 4 seconds of delay between each loop. There's no reasonable way a NVMe wouldn't have returned a PARTUUID by that time. While SSD's do..

**Comment by Torxed** [comment]
Reintroduced the logic of re-trying getting `PARTUUID` and `UUID` in the PartitionInformation model.
We'll have to clean up the logic of calling `_fetch_information()` on several places, but this is the most reliable way of making sure the PartitionInformation contains the information we want.

**Comment by Torxed** [comment]
This fix has been confirmed to work. There's still the underlying issue of `archinstall` becoming confused if all `PARTUUID`'s are `None`. In which case it doesn't know what to do and it shouldn't continue either. But some how it has mixed up two partitions for being the same and that is bad. But at least this addresses the immediate issue of people not being able to partition at all.

**Comment by jkbbwr** [comment]
Can confirm fix worked on my disk setup as well.

**Pull request merged**
