### PR TITLE
Fix 2253

### LINKED ISSUE #2253: [2.7.0] Proprietary nvidia not installed when chose nvidia-proprietary
Reproductibility : 

- Load archiso
- install pip
- pip install --upgrade archinstall --break-system-packages
- archinstall -version (2.7.0)
- setup default install KDE/systemd-boot
- select nvidia-proprietary
- reboot
- No nvidia packages installed on the system (but libvdpau is installed...)

Screenshot_20231123_122320

### PR DESCRIPTION
**Pull request by svartkanin**
This should fix #2253 and install the GFX driver correctly. 
Generally the whole gfx installation logic is coded very complicated and can be simplified in another PR

### CODE REVIEW

**Comment by svartkanin** [comment]
@Torxed the docs build is failing not sure if that should work already?

**Comment by Torxed** [comment]
Yeah I'll have a look at the docs, it's probably a setting on the project that changed. Good work on the PR in general.

**Comment by Torxed** [comment]
Where do we install the dkms btw and the -header packages?

**Comment by svartkanin** [comment]
@Torxed I linked it here https://github.com/archlinux/archinstall/issues/2253#issuecomment-1825129288 it's all a bit cryptic

**Comment by Torxed** [comment]
Aaah that's why I couldn't grep it ^^ Solid logic tho and I'll push a patch later tonight so it end up on the ISO ❤️

**Pull request merged**
