### PR TITLE
GitHub Actions: Build Arch Live ISO With Each Commit Included

### PR DESCRIPTION
**Pull request by dylanmtaylor**
Screenshot from 2021-04-10 17-49-08

VirtualBox_arch_10_04_2021_20_02_01

So this is a really neat CI/CD feature I'm testing out - we can have GitHub automatically build us ISOs to test to avoid having to replace ArchInstall on a vanilla Arch image. I want to get it to automatically launch as well - I think this will prove to be incredibly useful when done.

This will enable the following workflow when reviewing a change/pull request:

* Download ISO
* Start up VM or Write to USB
* The specific ArchInstall commit will be automatically installed and you can run it with python -m archinstall

### CODE REVIEW

**Comment by Torxed** [comment]
Just a ridiculous question before I merge.. Or two..
1. Is this allowed? Are we allowed to store 700+ MB worth of binary stuff on Github actions? @grazzolini?
2. Would every commit triggers this and would it remove the old ISO? Just making sure we're cleaning up after us.

**Comment by dylanmtaylor** [comment]
> Just a ridiculous question before I merge.. Or two..
> 
> 1. Is this allowed? Are we allowed to store 700+ MB worth of binary stuff on Github actions? @grazzolini?
> 2. Would every commit triggers this and would it remove the old ISO? Just making sure we're cleaning up after us.

So, for #1 I'm not sure but they don't seem to prevent it. It's automatically deleted after 90 days by default

**Comment by dylanmtaylor** [comment]
> Just a ridiculous question before I merge.. Or two..
> 
> 1. Is this allowed? Are we allowed to store 700+ MB worth of binary stuff on Github actions? @grazzolini?
> 2. Would every commit triggers this and would it remove the old ISO? Just making sure we're cleaning up after us.

It looks like on the project level we can change this to 14 days or so? Might make it so we're not 'abusing' GitHub's storage too much. It's a setting and not something you commit.

**Comment by dylanmtaylor** [comment]
This wording seems to indicate they're perfectly fine with it:

About billing for GitHub Actions
GitHub Actions usage is free for both public repositories and self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account. Any usage beyond the included amounts is controlled by spending limits

As a legitimate public open-source project I think we'll be okay.

**Comment by Torxed** [comment]
> This wording seems to indicate they're perfectly fine with it:
> 
> About billing for GitHub Actions
> GitHub Actions usage is free for both public repositories and self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account. Any usage beyond the included amounts is controlled by spending limits
> 
> As a legitimate public open-source project I think we'll be okay.

As long as we're not racking up a quota for Arch Linux public account some how, I'd be fine with this.
Just a note here that this project will eventually make it's way into the official GitLab when that opens up for the public, in which case we'll need to re-visit this and migrate it.

**Comment by dylanmtaylor** [comment]
> > This wording seems to indicate they're perfectly fine with it:
> > About billing for GitHub Actions
> > GitHub Actions usage is free for both public repositories and self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account. Any usage beyond the included amounts is controlled by spending limits
> > As a legitimate public open-source project I think we'll be okay.
> 
> As long as we're not racking up a quota for Arch Linux public account some how, I'd be fine with this.
> Just a note here that this project will eventually make it's way into the official GitLab when that opens up for the public, in which case we'll need to re-visit this and migrate it.

Migration is actually really easy for this; I have a ton of experience with GitLab runners from working with them professionally at work and could make a .gitlab-ci.yaml file for this in very little time. :) We just need a worker node hosted somwehere with a privileged Docker runner (to allow for it to build).

**Comment by grazzolini** [comment]
I think should be triggered only on master or when new PR's are submitted, not on each and every commit.

**Comment by dylanmtaylor** [comment]
> I think should be triggered only on master or when new PR's are submitted, not on each and every commit.

You are probably right but I do not know if that will retrigger the pipeline if you amend a pull request with additional commits

**Comment by grazzolini** [comment]
I've seen it being done on other projects, so I think it's possible.

**Comment by dylanmtaylor** [comment]
> I've seen it being done on other projects, so I think it's possible.

Let me do a quick test. I will make a new commit to this pull request and change it so it just runs on pull requests and see if it runs with the additional commit.

**Comment by dylanmtaylor** [comment]
Okay so it looks like that works. I'm fine with changing it, and it's probably okay to go in now. It's not like this can possibly break the library itself.

**Comment by Torxed** [comment]
> Okay so it looks like that works. I'm fine with changing it, and it's probably okay to go in now. It's not like this can possibly break the library itself.

Instead of closing and re-opening, I wouldn't mind the PR being marked as WIP, helps out with knowing what's being worked on and what's tested and done. But it looks good with `pull_request` so I'm merging :) Consider this the first official test of the runner hehe.

**Comment by dylanmtaylor** [comment]
> > Okay so it looks like that works. I'm fine with changing it, and it's probably okay to go in now. It's not like this can possibly break the library itself.
> 
> Instead of closing and re-opening, I wouldn't mind the PR being marked as WIP, helps out with knowing what's being worked on and what's tested and done. But it looks good with `pull_request` so I'm merging :) Consider this the first official test of the runner hehe.

Didn't mean to close and re-open, these buttons are too close together to try to reply on mobile and it doesn't offer confirmation. :(

**Comment by Torxed** [comment]
I did just realize something tho, and that is: Does every PR trigger this *before* being merged? Wouldn't that mean if I spawn two PR's, the last one will overwrite the ISO? I guess this isn't an issue, but a bit weird for testing purposes. Not knowing which ISO i get.

**Comment by dylanmtaylor** [comment]
> I did just realize something tho, and that is: Does every PR trigger this _before_ being merged? Wouldn't that mean if I spawn two PR's, the last one will overwrite the ISO? I guess this isn't an issue, but a bit weird for testing purposes. Not knowing which ISO i get.

It's not an overwrite. Each has it's OWN iso file :)

**Comment by Torxed** [comment]
> > I did just realize something tho, and that is: Does every PR trigger this _before_ being merged? Wouldn't that mean if I spawn two PR's, the last one will overwrite the ISO? I guess this isn't an issue, but a bit weird for testing purposes. Not knowing which ISO i get.
> 
> It's not an overwrite. Each has it's OWN iso file :)

Awesome! Again, this is some what of black magic to me.
But that is great to hear, and I'm glad it's not on each commit heh.

**Pull request merged**
