### PR TITLE
https://github.com/archlinux/archinstall/suites/6958817854/artifacts/271610473

### PR DESCRIPTION
**Pull request by aavitiacat**
🚨 PR Guidelines:

# New features *(v2.2.0)*

All future work towards *`v2.2.0`* is done against `master` now.<br>
Any patch work to existing versions will have to create a new branch against the tagged versions.

# Describe your PR

If the changes has been discussed in an Issue, please tag it so that we can backtrace from the issue later on.<br>
If the PR is larger than ~20 lines, please describe it here unless described in an issue.

# Testing

Any new feature or stability improvement should be tested if possible. Please follow the test instructions at the bottom of the README or use the ISO built on each PR.

### CODE REVIEW

**Comment by svartkanin** [comment]
What is the point of opening this open PR again?

**Comment by dylanmtaylor** [comment]
> What is the point of opening this open PR again?

I have no idea. I'm surprised it even shows a delta against master. And the link is just a hyperlink to the ISO...

**Comment by dylanmtaylor** [comment]
> Seems like a bot, @Torxed any way to block this?

Let's just close the PR

**Comment by Torxed** [comment]
Agreed, not sure where we would ever need to mess with cpufreq tbh :)

**Pull request closed without merging**
