### PR TITLE
Integrate new curses menu

### PR DESCRIPTION
**Pull request by svartkanin**
Integrate the new curses menu into archinstall and replace all 3rd party menu usages with the custom curses implementation.

https://github.com/user-attachments/assets/9bb7bd59-504e-44e6-ab7b-43f2c5126db7

- [x] Replace all existing `simple-term-menu` usages with custom curses implementation
- [x] Add preset value for text inputs
- [x] Test all menu options for preview and preset values
- [x] Replace all print statements with either debug or custom curses print

### CODE REVIEW

**Comment by svartkanin** [comment]
@Torxed I think this is now ready for a full review

**Comment by svartkanin** [comment]
`swiss.py` script has also been adapted now

**Comment by Torxed** [comment]
Running a few last tests, and I can't tell if it's the code in `master` yet or this PR, but https://github.com/archlinux/archinstall/issues/2793 is blocking a release.

I'm running out of time for more tests for today.
I'll continue tomorrow unless you have a moment to double check @svartkanin?

**Review by Torxed — APPROVED** [review]
Awesome work! I'll rerun a few tests against master with the disk issue but other then that let's get a new version out!

**Pull request merged**
