### PR TITLE
Update instructions to run archinstall from ISO

### PR DESCRIPTION
**Pull request by svartkanin**
Small improvements to the instructions how to run a branch on a live ISO

### CODE REVIEW

**Comment by Torxed** [comment]
Perhaps we should mention `copytoram=y` which will use 75% of RAM to facilitate the tmpfs. Which should allow us to more reliably recommend upgrades and installs.

Docs: https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio-archiso/-/blob/master/docs/README.bootparams#L26

**Comment by svartkanin** [comment]
Ahh nice I'll add that

**Comment by codefiles** [comment]
This may also be relevant:
https://wiki.archlinux.org/title/Archiso#Adjusting_the_size_of_root_partition_on_the_fly

**Comment by Torxed** [comment]
The later might be faster actually, that way the user don't need to copy the root content to the tmpfs initially.

**Comment by svartkanin** [comment]
Added the on-the-fly instructions as well

**Pull request merged**
