### PR TITLE
Issue #764 Modify inclusion of self.BINARIES entry due to a mistype 

### PR DESCRIPTION
**Pull request by wllacer**
It's simply a oneliner

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
@Torxed  do we have time to get this in before tagging?

**Review by dylanmtaylor — APPROVED** [review]

**Comment by wllacer** [comment]
Hope it didn't came in ... the real solution is exactly the reverse. (not btrfs-progs, but btrfs is what we need to search for. I still can't boot in my test enviroment but comparing with the "real" one gave me the clue
I've made the update

**Comment by Torxed** [comment]
Good catch, I don't know how any of the BTRFS installations have worked at all without this.. Luck?

**Comment by wllacer** [comment]
No. Whatever is in the binaries is only really needed if the root FS is not available ... and then probably you are in the need of a recovery tool.
OTOH noone pays attention to the messages on mkinitcpio building ... They were too obvious

**Pull request merged**
