### PR TITLE
Fix hyprland typo in file, classname, string

### PR DESCRIPTION
**Pull request by TheChuckster**
- This fix issue: #2007

## PR Description:

Rename desktop class and fix string value.

## Tests and Checks
- [x] I have tested the code!<br>

### CODE REVIEW

**Comment by TheChuckster** [comment]
Waiting for CI approval to obtain test ISO

**Comment by TheChuckster** [comment]
Built and tested ISO in VM, it works:
2023-08-12-070615_1920x1080_scrot

**Comment by TheChuckster** [comment]
Bump for review / merge?

**Comment by Torxed** [comment]
Thank you for the PR, We've got a few different PR's on this, just need to clean up among the PR's and merge one of them!

**Comment by svartkanin** [comment]
Thanks for the change, there were quite a few other PRs fixing this as well so we'll go ahead with https://github.com/archlinux/archinstall/pull/1824 as it fixes more things

**Pull request closed without merging**
