### PR TITLE
Remove `select_language()` duplicate of `select_kb_layout()`

### LINKED ISSUE #2150: Functions `select_language()` and `select_kb_layout()` are identical
https://github.com/archlinux/archinstall/blob/edbc13590366e93bb8a85eacf104d5613bc5793a/archinstall/lib/interactions/general_conf.py#L88-L111

https://github.com/archlinux/archinstall/blob/edbc13590366e93bb8a85eacf104d5613bc5793a/archinstall/lib/locale/locale_menu.py#L132-L155

The function `select_language()` is not used.

The function `select_kb_layout()` is used once:

https://github.com/archlinux/archinstall/blob/edbc13590366e93bb8a85eacf104d5613bc5793a/archinstall/lib/locale/locale_menu.py#L90

### PR DESCRIPTION
**Pull request by codefiles**
Resolves #2150

### CODE REVIEW

**Comment by Torxed** [comment]
Should we add a deprecation warning and possible route users to the real function first? As we have a few library users who might use it without us being able to check if they do.

**Comment by codefiles** [comment]
Makes sense. Could you proceed with that?

**Comment by svartkanin** [comment]
There should be a deprecated decorator in the code somewhere to mark the functions

**Comment by codefiles** [comment]
> There should be a deprecated decorator in the code somewhere to mark the functions

I thought I had seen a deprecated function with that or something like it used in the code somewhere before. I looked before submitting and could not find anything like that or I would have replicated it.

@Torxed or @svartkanin, would either of you submit a pull request to close the issue with the suggested deprecation procedures?

**Comment by Torxed** [comment]
I was thinking of submitting a commit to this PR as this PR is pretty good. Give me a day :)

**Comment by Torxed** [comment]
I believe this transparent call will suffice for now, with a `warn()` on future removal.
And later we'll raise an exception before finally removing the function alltogether.

**Pull request merged**
