### PR TITLE
Some very minor cleanup

### PR DESCRIPTION
**Pull request by dylanmtaylor**
Tiny post-merge fixes.

### CODE REVIEW

**Comment by l4zy0n3** [comment]
@dylanmtaylor, I merged the wrong path for config file in Readme, could you include the fix for that in this one

**Review by Torxed — CHANGES_REQUESTED** [review]
Time is used: https://github.com/archlinux/archinstall/blob/f5fb8e3bdd6293ed9b873004cf63c4eaba16f2ca/archinstall/lib/disk.py#L259

**Comment by dylanmtaylor** [comment]
Dropped commit that deleted time import

**Comment by dylanmtaylor** [comment]
> @dylanmtaylor, I merged the wrong path for config file in Readme, could you include the fix for that in this one

Fixed. Ready to go in, @Torxed.

**Comment by l4zy0n3** [comment]
> > @dylanmtaylor, I merged the wrong path for config file in Readme, could you include the fix for that in this one
> 
> Fixed. Ready to go in, @Torxed.

Noice

**Comment by dylanmtaylor** [comment]
> Time is used:
> 
> https://github.com/archlinux/archinstall/blob/f5fb8e3bdd6293ed9b873004cf63c4eaba16f2ca/archinstall/lib/disk.py#L259

Screenshot from 2021-05-19 17-28-49

Kind of odd that PyCharm thinks it is not... oh well. I'll leave it for now.

**Pull request merged**
