### PR TITLE
Update binary.rst

### PR DESCRIPTION
**Pull request by Medusas-rorriM**
added italics to the warning word

- This fix issue: 

## Tests and Checks
- [ ] I have tested the code!<br>

### CODE REVIEW

**Comment by Medusas-rorriM** [comment]
added italics to the warning word in the doc

**Comment by svartkanin** [comment]
@Torxed I reckon this is fine

**Comment by Torxed** [comment]
I believe I've removed this section in https://github.com/archlinux/archinstall/pull/1967, do we still want to merge this in the meantime?

**Comment by svartkanin** [comment]
In that case it's redundant :)

**Comment by svartkanin** [comment]
@Medusas-rorriM thanks for the change but this section will be removed in an ongoing PR

**Pull request closed without merging**
