### PR TITLE
Add network-manager-applet to NetworkManager profile

### PR DESCRIPTION
**Pull request by kpcyrd**
This adds the network-manager-applet package to the NetworkManager profile. :)

### CODE REVIEW

**Comment by Torxed** [comment]
I would prefer if the package was not installed unless a desktop profile was installed.

**Comment by dylanmtaylor** [comment]
> I would prefer if the package was not installed unless a desktop profile was installed.

Same, and I don't think all desktop environments using networkmanager would use this package.

**Comment by kpcyrd** [comment]
I think we'd need some kind of solution for the i3 profile, because it's currently not possible to connect to a wifi through the gui if this package isn't present. :)

**Comment by Torxed** [comment]
Just a friendly reminder:
> Your branch is ahead of 'origin/master' by 1662 commits.

I pulled in our master into your branch and it was a bit behind.
You can solve this by doing:
```
$ cd archinstall
$ git checkout master
$ git remote add upstream https://github.com/archlinux/archinstall.git
$ git pull upstream master
```
And then you can continue your normal workflow of doing `git checkout -b new-branch` and it should contain our latest changes.
Or just do `git pull upstream master` if you forget before creating the branch :)

I'm taking a look at this PR now.

**Comment by Torxed** [comment]
Thank you for submitting this PR.
I tweaked it a tiny bit to look for the chosen profile through `storage["arguments"]`, as the configuration has been stripped down to only the related network configuration in the nic config model :)

**Pull request merged**
