### PR TITLE
Improve EFI bootloader installation

### PR DESCRIPTION
**Pull request by HTV04**
## PR Description:

Some improvements to the installation of bootloaders on devices with UEFI:
* GRUB:
  * Adjusted the grub-install parameters
    * Disabled the `--bootloader-id` option, using the default `grub` instead
    * Disabled the `--debug` option, which prints a lot of unnecessary info and may enable a [debug](https://github.com/rhboot/grub2/blob/72b17102c157707acfffb01ae7694de6cf23eb5c/util/grub-install.c#L228) [flag](https://github.com/rhboot/grub2/blob/72b17102c157707acfffb01ae7694de6cf23eb5c/util/grub-install.c#L861)
    * Disabled the `--removable` option, which prevents an EFI entry from being created
      * The other functionality of this option, setting the destination EFI file to the standard `/EFI/BOOT/BOOTxxx.EFI/`, has been implemented manually
* Limine:
  * An EFI entry is now added via `efibootmgr`
* EFISTUB
  * Code clarity tweaks
* All bootloaders:
  * Like GRUB, all bootloaders will now attempt to install again upon failure to assist with buggy EFIs
    * After two failed attempts, the installer will attempt to use a fallback without EFI variables; if this fails, the installer will error out
  * Added a few debug messages for silent errors

## Tests and Checks
- [x] I have tested the code!<br>

### CODE REVIEW

**Comment by vanillaSprinkles** [comment]
would it be possible to give the user a prompt, upon ultimate failure, to abort advancing on the entirety of the archinstall scripts, or to continue with a potentially failed grub-install? (or check for an archinstall flag to allow prompt/silent mode or something) - suggested grub-install errors as a my example in https://github.com/archlinux/archinstall/issues/2378

**Comment by Torxed** [comment]
Awesome work, I'd like to marge this.
I'm wondering if we'll bring back this tho: https://github.com/archlinux/archinstall/pull/793

**Comment by HTV04** [comment]
> Awesome work, I'd like to marge this. I'm wondering if we'll bring back this tho: #793

I believe that "fixed" the issue because it prevented grub-install from adding the EFI entry in the first place. Instead, the removable flag treats the destination as a removable drive, only adding a standard `BOOTX64.EFI` file.

Also, this PR might actually fix that issue due to automatically retrying the installation upon such an error.

**Comment by HTV04** [comment]
> would it be possible to give the user a prompt, upon ultimate failure, to abort advancing on the entirety of the archinstall scripts, or to continue with a potentially failed grub-install? (or check for an archinstall flag to allow prompt/silent mode or something) - suggested grub-install errors as a my example in #2378
> 
> edit; i tested this on an ipxe'd bios-install and it has still failed (dropped it on top of the current installer.py, did not check for rebase'ing ect) ( it = https://github.com/archlinux/archinstall/blob/5b9574d3acbe5a106543e16d5cc02e1ed860d7b1/archinstall/lib/installer.py )

I could try, but it would make the installation process less "automatic." This might be in the scope of a future PR to handle common errors during installation.

**Comment by Torxed** [comment]
I could never get a hold of hardware that could trigger the error.
I'm totally fine adding in this PR considering the try/except which should fallback to trying.

And now that we know about the issue, if it comes back we could add back this flag.

**Comment by vanillaSprinkles** [comment]
im wondering now if adding different behaviors for each type of error would be useful? for example for my "fun" hardware the efibootmgr can fail but is not an issue due to having to teak the bios manually anyways; and skipping it by adding `--no-nvram`  to grub-install might be useful (something like that is where a user-prompt maybe okay vs auto-skip (or the never ending add-more-flags/inputs))

**Comment by Torxed** [comment]
Those checks and tweaks would improve reliability if nothing else, and it's a godsend if we could get there. Because this and disk operations have always been a painpoint.

**Pull request closed without merging**
