### PR TITLE
Created dwm.py

### PR DESCRIPTION
**Pull request by Dark-Kernel**
Created dwm.py for suckless users.

- Added new dwm.py at archinstall/default_profiles/desktops/.

## PR Description:

This will make easier for the dwm users to setup their suckless environment.

## Tests and Checks
- [ ] I have tested the code!<br>

### CODE REVIEW

**Review by lavafroth — APPROVED** [review]
Looks good!

**Comment by Torxed** [comment]
hmm indentation error, didn't caught that on the phone.

**Comment by codefiles** [comment]
Suckless software is intended to be customized through modification of the source code and built by the user. This is why `dwm` and `st` are not in the Arch Linux official repositories but can be found in the AUR. Since these packages are not in the Arch Linux repos and the AUR is not supported I recommend reverting.

**Comment by lavafroth** [comment]
@codefiles is correct. I looked into the [dwm ArchWiki](https://wiki.archlinux.org/title/Dwm) and it seems that `dwm` is only available through the AUR. Since we don't have or plan to employ an AUR helper, we might want to revert this.

It's better `dwm` users consider a minimal installation and build it from source or use an AUR helper like `paru`.

**Comment by Dark-Kernel** [comment]
Sorry I didn't noticed 😅, And thank you for your consideration. 

But, why we couldn't use AUR?
Yes, I know suckless software is intended to be installed from source, but we can do that thing for the users? 
And after installation they can manually updated and patch their `dwm` and other suckless tools according to them. 
My idea was to giving the base to the user, which can make easier for them.

Anyway Thanks.

**Comment by lavafroth** [comment]
If we try to package an AUR helper alongside the installer, it would open up a whole new can of worms for the "additional packages" section. Sure, users would then be able to install `dwm` and `dwm-git` but they'd probably also be tempted to install proprietary packages like Spotify or Google Chrome without realizing that those AUR packages are probably maintained by third parties and individuals.

I'm not dunking on third party AUR maintainers by any means but I think that new users should at least be aware of what they're installing. Final verdict goes to @Torxed, maybe he can explain this better than me.

**Comment by Dark-Kernel** [comment]
Thanks, understood.

**Comment by Torxed** [comment]
I agree, and I missed that it was an AUR package. But now that it's mentioned I recall we had discussions about this profile before and agreed to not include it. I'll revert, apologies!

**Pull request merged**
