### PR TITLE
Sway profile - select seat

### PR DESCRIPTION
**Pull request by bd-g**
This is perhaps a more fleshed out option to resolve #1626 

## PR Description:

This PR adds a selection menu when selecting the sway profile that allows the user to either install polkit or seat. One of the two is required for sway to run, so we should prompt the user to choose one when installing sway.

## Tests and Checks
- [x] I have tested the code! I ran on the v2.5.3 ISO and testing the following installation flows:
    - Installing sway profile with polkit
    - Installing sway profile with seatd
    - Selecting sway profile with seatd/polkit, then clearing selection
    - Selecting sway profile with seatd/polkit, then clearing selection and selecting KDE

### CODE REVIEW

**Comment by bd-g** [comment]
Updates? (Only asking since contributing guidelines say to recomment if thread goes stale)

**Comment by Torxed** [comment]
I've been meaning to test this after the discussions in #1626
ETA this weekend :)

**Comment by Torxed** [comment]
Tested and it works.
I have no idea how to get out of sway so that was an interesting test :P

**Comment by Torxed** [comment]
Great work btw!

**Pull request merged**
