### PR TITLE
Fix load_devices() lsblk

### LINKED ISSUE #1993: Archinstall encounters Error when starting - "/dev/sda3: not a block device"
`exited with abnormal exit code [32]: lsblk: /dev/sda3: not a block device`

When I start archinstall, it exists after a few seconds with the mentioned error.
I tried the newest package from the Arch Repos, and I tried the scripts from the master branch, but regardless this error occurrs.
IMG_20230806_222932

Running lsblk shows that sda doesn't have a 3rd partition which puzzles me.
sda isn't even relevant I  what I was going to do. I want to install Arch on a different device. Is there any way to make archinstall ignore this or is temporarily removing the drive the only solution?

### PR DESCRIPTION
**Pull request by codefiles**
Fixes #1993

- Get all lsblk info and search it rather than making several calls to lsblk
- Add udev sync before lsblk call

### CODE REVIEW

**Review by svartkanin — APPROVED** [review]

**Comment by svartkanin** [comment]
Thanks for the fix, @codefiles the PR is in draft, is there anything left?

**Comment by codefiles** [comment]
After submitting I noticed that when a user has an existing btrfs partition and it is not mounted then `get_btrfs_info()` will call `mount()`. I think this patch will just move the bug to the lsblk call in `mount()` given that case.

Maybe using `udevadm settle` to synchronize with udev is needed after `newDisk()` and `freshDisk()`. Take a look at the output of `udevadm monitor --udev` while executing those within the python interpreter. You see udev events, right? I think they could be causing a race condition with the lsblk calls that follow. What do you think?

**Comment by svartkanin** [comment]
I wonder if enforcing a restart after a successful installation or at least preventing to run it multiple installations might be worth exploring?

**Comment by codefiles** [comment]
This does not fix the issue it was intended to but I am fine with it being merged.

@svartkanin, in regards to the linked issue, I do not agree with your conclusions or suggestions but thanks.

**Comment by codefiles** [comment]
I figured out how to reproduce the bug. I added an additional commit and with that the bug should be fixed.

**Review by Torxed — APPROVED** [review]

**Review by svartkanin — APPROVED** [review]

**Comment by Torxed** [comment]
Nicely done, was it tricky to reproduce the bug?

**Comment by codefiles** [comment]
From https://github.com/archlinux/archinstall/issues/2536#issue-2349753573 the traceback shows this bug happens during an lsblk call in `load_devices()`:

```
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 5, in <module>
    from archinstall import run_as_a_module
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 11, in <module>
    from .lib import disk
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/__init__.py", line 1, in <module>
    from .device_handler import device_handler, disk_layouts
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 649, in <module>
    device_handler = DeviceHandler()
                     ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 38, in __init__
    self.load_devices()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 74, in load_devices
    lsblk_info = get_lsblk_info(partition.path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_model.py", line 1136, in get_lsblk_info
    if infos := _fetch_lsblk_info(dev_path):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_model.py", line 1121, in _fetch_lsblk_info
    raise DiskError(f'Failed to read disk "{dev_path}" with lsblk')
archinstall.lib.exceptions.DiskError: Failed to read disk "/dev/sda1" with lsblk
```

The function `load_devices()` is called when the application launches and I had seen the bug before from my own testing. I put the function call in an infinite loop.

```patch
diff --git a/archinstall/lib/disk/device_handler.py b/archinstall/lib/disk/device_handler.py
index 8d38dbc8..6db3d94b 100644
--- a/archinstall/lib/disk/device_handler.py
+++ b/archinstall/lib/disk/device_handler.py
@@ -38,7 +38,8 @@ class DeviceHandler(object):

        def __init__(self):
                self._devices: Dict[Path, BDevice] = {}
-               self.load_devices()
+               while True:
+                       self.load_devices()

        @property
        def devices(self) -> List[BDevice]:
```

With this patch I am able to produce the bug with the commit previous to this merge by executing archinstall and letting this loop run until the error is raised. It takes a relatively short amount of time till the error is raised.

I then used that same process to check this pull request with a small addition. I used `tail -f /var/archinstall/log/install.log | grep -E '(Device|Partition) lsblk info not found'` in another tty while the application was running. This was to verify that no devices or partitions were skipped due to missing lsblk infomation since that is a feature of this pull request. Without the last commit to this pull request there were skips but after adding it there were no skips and no error raised.

#2536 and #2559 can be closed as well.

**Pull request merged**
