### PR TITLE
Replace os.system with subprocess.call

### PR DESCRIPTION
**Pull request by JakobDev**
os.system should not be used anymore.

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
Is there any benefit of doing it this way? os.system() worked fine in that case.

**Comment by advaithm** [comment]
@dylanmtaylor officially os.system is depreciated and can/will be removed in the future

**Comment by dylanmtaylor** [comment]
> @dylanmtaylor officially os.system is depreciated and can/will be removed in the future

No objections from me. Seems like a sensible change.

**Comment by Torxed** [comment]
This is what you get for starting writing the code 5 years ago.
Nice catch and there's probably more low hanging fruit hanging around that we should take a look at :)

**Pull request merged**
