### PR TITLE
Rework the user/superuser configuration

### PR DESCRIPTION
**Pull request by svartkanin**
This addresses #986.

This is reworking the user/superuser configuration flow.
Previously the root password and superusers where mutually exclusive (kinda), one could only select a root password or a superuser. However, there was a sneaky way to get around this by simply setting a root password and then creating a user and promoting them to superuser. 

With these changes:
- Allow both a root password and a superuser to be configured
- Allow to configure multiple superusers at the same time via the superuser menu entry
- Downgrade the user select to be only a user select

### CODE REVIEW

**Comment by wllacer** [comment]
There is a use case you should check. When the same userid appears in both lists.  Now it is very difficult to check (or at least ugly coding) and -honestly- i have no idea what the result would be.
I think long term we should only have one list (dict) with a sudoer attribute to distinguish each case. I'm doing some work around it in my attempt to keep previous values, and -although i'm now stuck because some UI design issues, so it is not for the short term- using it internally. The format conversion is a bit ugly, but gives a lot of flexibility of use

**Comment by Torxed** [comment]
> I think long term we should only have one list (dict) with a sudoer attribute to distinguish eac

I think the result would be that it will simply try to create the user twice, which should be accepted but errors ignored.
And in the second/first attempt of creating it as a super-user, it will simply create a `/etc/sudoers.d/entry` making either the new or existing user a sudo user :)

**Comment by svartkanin** [comment]
> I see you have done away with the forced parameter for superusers. It was there to "force" the existence of having at least one superuser if no root password was specified. I miss this control in your code.
It is treated at _missing_config, and thus in the exec_func of install. I have the feeling that I missed something in such a case (not two options can be none). Please have a look at it and give me your opinion

The thing I have removed was that the superuser entry does no longer depend on the root password config by removing the `dependencies_not` which served as a XOR for root password <-> superuser. 
The missing configuration check remained as is and I don't change anything there (except for removing the timezone check because we have a default value there now). 
Please let me know if you think any logic got messed up with the changes

**Comment by svartkanin** [comment]
Are there any concerns with this left?

**Comment by Torxed** [comment]
Dont think so :) will merge during the day

**Comment by Torxed** [comment]
Maybe the `x: self...` should have been there >_O

**Pull request merged**
