### PR TITLE
Cleanup partition

### PR DESCRIPTION
**Pull request by svartkanin**
This should cleanup the partition class a bit and make things for removing the native types soon.

### CODE REVIEW

**Comment by svartkanin** [comment]
Since this PR was still open I pushed more updates to the partitioning into here. 

I have tested that archinstall can still 
- Create ext4 partitioning
- Create btrfs partitioning
- Create encrypted partitions

Since this is quite dangerous update I'd really like to have someone test this as well since it is the essence of the whole cli :)

**Comment by svartkanin** [comment]
I'm going to claim (without proof) that these changes might solve: 
- https://github.com/archlinux/archinstall/issues/1181

**Comment by Torxed** [comment]
Thank you, as always nice work! I'm starting to pull in all the PR's and master will be a bit unstable while I do this (for anyone reading the latest activity on the repo)

**Comment by Torxed** [comment]
I think this PR might have introduced: https://github.com/archlinux/archinstall/issues/1411
I'm trying to figure out exactly why.

Because we still have `BlockDevice.partitions`.

**Comment by Torxed** [comment]
It appears there's a setback here: https://github.com/archlinux/archinstall/blob/3842f1eb5644851ad3af84d84e704c0b33b2b204/archinstall/lib/installer.py#L1001-L1002

Where we no longer get the `BtrfsPartition()` objects, but instead `Partition()` which only has one mountpoint available, and it will be `/var/log/archinstall/var/log` instead of the different nuances that btrfs subvolumes can be mounted at, sharing the same partition.

**Comment by Torxed** [comment]
Trying to think of the best approach forward here.
Because technically those paths are on that partition, so that's not a lie.
But that partition doesn't have a mountpoint, because the subvolumes do.

**Comment by svartkanin** [comment]
@Torxed yeah sorry about the bugs, I can take a look at this today :)

**Comment by svartkanin** [comment]
@Torxed I saw that you have already merged in 2 fixes, is there anything outstanding?

**Comment by Torxed** [comment]
I think it's all good :D I mostly commented to track the relationship between the too.
It was really easy to miss this and I didn't pick up on it during merging so it's on me!

**Pull request merged**
