### PR TITLE
Modify setuptools configuration to fix development ISOs

### PR DESCRIPTION
**Pull request by dylanmtaylor**
This should close issue #968

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
This *seems* to work. Instead of erroring out, I'm now able to launch archinstall from the development ISO.
VirtualBox_Arch_12_02_2022_12_35_28
VirtualBox_Arch_12_02_2022_12_34_52

**Comment by dylanmtaylor** [comment]
It's a major improvement at least, considering it starts now. :) Still some crashes, like when selecting a DE (GNOME in this case):
VirtualBox_Arch_12_02_2022_12_38_00

Also crashes when trying to select a language.
VirtualBox_Arch_12_02_2022_12_39_26

**Comment by dylanmtaylor** [comment]
Okay, so it's not copying recursively... eww. Going to need to come up with a solution here.

**Comment by Torxed** [comment]
Can we get this to imclude the profiles/ as well?

**Comment by dylanmtaylor** [comment]
> Can we get this to include the profiles/ as well?

They appear to be already there. This is using setuptools instead of flit so doesn't address that issue.
VirtualBox_Arch_12_02_2022_12_55_15

**Comment by Torxed** [comment]
Ah! You are correct!

**Pull request merged**
