### PR TITLE
Add hostname and locales as parameters to `minimal_installation()`

### PR DESCRIPTION
**Pull request by codefiles**
- This resolves: https://github.com/archlinux/archinstall/issues/1200#issuecomment-1130564952

## PR Description:

Fix occurrence of duplicate calls to `set_hostname()` and `set_locale()` by adding hostname and locales as parameters to `minimal_installation()`.

## Tests and Checks
- [ ] I have tested the code!

### CODE REVIEW

**Review by Torxed — APPROVED** [review]
Looks solid! Merging in a few days.

**Comment by codefiles** [comment]
I can't get the flake8 linting to pass. What would be the acceptable way to format the long if statement in `examples/guided.py`?

**Comment by codefiles** [comment]
Updated this pull request to use locales instead of locale in preparation of pull request to add support for https://github.com/archlinux/archinstall/issues/1435.

**Comment by Torxed** [comment]
Great work and thank you for being patient with me! I finally got around to merge some PR's!

**Pull request merged**
