### PR TITLE
po: update Tamil translation

### PR DESCRIPTION
**Pull request by kbdharun**
## PR Description:

Update Tamil translation, continuation of https://github.com/archlinux/archinstall/pull/2096#issuecomment-1732449779

## Tests and Checks
- [ ] I have tested the code!<br>

### CODE REVIEW

**Comment by kbdharun** [comment]
Will run the script and mark this PR for review.

**Comment by Torxed** [comment]
Please avoid adding languages other than the one you want to target :) makes it a lot easier for us to avoid conflicts if multiple PR's come in with translation updates and helps other contributors too :)

If possible, can you reset and un-add all other translations including the main .po file?

**Comment by svartkanin** [comment]
@Torxed that's unfortunately necessary to fulfil the check. Running the bash script will make sure everything is up to date and reduce conflicts, hopefully.

I don't think there is a way to only target a specific language when pulling in new translations

**Comment by kbdharun** [comment]
> Please avoid adding languages other than the one you want to target :) makes it a lot easier for us to avoid conflicts if multiple PR's come in with translation updates and helps other contributors too :)
> 
> If possible, can you reset and un-add all other translations including the main .po file?

Yes I am aware of not updating other translations as it would cause conflicts (I did exactly this in my initial commit and later added other changes after failed check). 

> @Torxed that's unfortunately necessary to fulfil the check. Running the bash script will make sure everything is up to date and reduce conflicts, hopefully.
> 
> I don't think there is a way to only target a specific language when pulling in new translations

This is exactly why this script is infeasible as it would require the translator or maintainer to run the script everytime after rebase to merge the PR. It wouldn't be able to fix conflicts with PO files on unmerged PRs and can sync with the master branch only i.e Let's say I created a PR for language A and ran the script which added updated strings for language B, and another translator for language B did the same now you have 2 files you need to manually fix the conflict before merging.

An alternative is dropping the script based workflow and suggesting translators use POedit's "Sync with source" option to sync with source POT file. This would update the language's MO file alone.

The best approach for managing translations would be using localisation platform (as I suggested a few months ago), there are FOSS platforms like Weblate, and proprietary ones like Crowdin and Transifex which are popular among translators. 

Since we are dealing with gettext PO files, Weblate has one of the most diverse feature set for this. It has add-ons to generate MO files automatically and you can even set it up to sync PO files with POT files, or even POT files with source string locations. It enforces quality check for translations too for common errors which we currently can't detect with a manual workflow. As a added bonus it adds translators as co-authors in commits so their contribution shows up in their GitHub activity feed. Weblate offers a libre plan for Foss projects which would be a perfect fit for archinstall.

Let me know if you want to know more, I will join the Discord server (my username is @ kbdk)

**Comment by svartkanin** [comment]
That does sound quite interesting, I'll have to dive into that a bitore

**Comment by kbdharun** [comment]
Noticed, That a fix has been made for the script. Will revert the last commit and rebase the PR.

**Review by Torxed — APPROVED** [review]

**Comment by kbdharun** [comment]
Feel free to Squash and Merge this PR, I have no idea how there is a change in the French page even after I reverted the commit.

**Comment by Torxed** [comment]
> Feel free to Squash and Merge this PR as the commit history has gotten a bit messy, I have no idea how there is a change in the French page even after I reverted the commit (but since it's an addition with no conflicting PRs I guess it is fine).

Yeah that should be fine, PR looks good from my point of view

**Pull request merged**
