### PR TITLE
Write user configuration JSON to a file in logs directory

### LINKED ISSUE #525: Add feature to write out config to file in logs dir w/ credentials stripped
I was thinking about adding this feature. Probably should go here:

https://github.com/archlinux/archinstall/blob/4bb644bf5b8ce70bc08c76deeeb6fe71a3c36c1a/examples/guided.py#L261

### PR DESCRIPTION
**Pull request by dylanmtaylor**
Closes #525 - untested, so it's a draft.

### CODE REVIEW

**Comment by l4zy0n3** [comment]
image
We need to find a way to accept both dict and string as valid mirror-region values, otherwise this won't work

**Comment by l4zy0n3** [comment]
also, seeing a weird # character when doing a cat on the file
image

**Comment by l4zy0n3** [comment]
> image
> We need to find a way to accept both dict and string as valid mirror-region values, otherwise this won't work

image
same issue with profile too

**Comment by l4zy0n3** [comment]
> Closes #525 - untested, so it's a draft.

Tested with both dict and string in chroot, generated config successfully installs. ^_^

**Comment by Torxed** [comment]
> image
> We need to find a way to accept both dict and string as valid mirror-region values, otherwise this won't work

If we can't get it working, I suggest the original as it's more flexible and granular. A single string is cleaner, but function over simplicity in this case.

**Comment by l4zy0n3** [comment]
> > image
> > We need to find a way to accept both dict and string as valid mirror-region values, otherwise this won't work
> 
> If we can't get it working, I suggest the original as it's more flexible and granular. A single string is cleaner, but function over simplicity in this case.

Both dict and string are working now

**Comment by l4zy0n3** [comment]
> > Closes #525 - untested, so it's a draft.
> 
> Tested with both dict and string in chroot, generated config successfully installs. ^_^

Tested

**Comment by Torxed** [comment]
Then I'll bring this into the tag!

**Pull request merged**
