### PR TITLE
Create a bspwm profile

### PR DESCRIPTION
**Pull request by j-james**
This PR adds a minimal bspwm installation to the collection of desktop profiles. It hasn't yet been tested.

### CODE REVIEW

**Comment by Torxed** [comment]
This has been marked as WIP for a while now, if it’s ready I’d be happy to merge it :)

**Comment by j-james** [comment]
Whoops, I kind of forgot about this... I'll work on polishing it up and bringing it up to date with `master` in the next few days.

**Comment by edl2** [comment]
> Whoops, I kind of forgot about this... I'll work on polishing it up and bringing it up to date with `master` in the next few days.

Bump. It's been a while, if you don't plan on finishing soon I can look into doing it, just let me know.

**Comment by Torxed** [comment]
Thank you for the contribution!
I'll run a few tests but it looks good just looking at it : )

**Pull request merged**
