### PR TITLE
Update locale files with ./locales_generator.sh to be current

### PR DESCRIPTION
**Pull request by JoelLarson**
# Update locale files with locales_generator.sh

The locales directory has become out of date. This PR updates the files by running `./locales_generator.sh` with no additional changes.

This change is to simplify https://github.com/archlinux/archinstall/pull/1341

### CODE REVIEW

**Comment by Torxed** [comment]
Apologies for the delay, I've waited with merging in the translations as we've moved around a lot of other stuff in prep for release.

Looking at this, to the untrained eye, what's the difference to #1341?
Is the only difference that you've executed `./locales_generator.sh` before translating and the other one did not?

**Comment by JoelLarson** [comment]
Yep! The Danish translations PR updated most of the Russian translations. This PR was to make it easier to review to make #1341 easier to merge.

**Comment by Torxed** [comment]
I'm not sure this specific PR is required as a lot of other languages pulled in these updates as well.
Could you rebase with master and check? Otherwise we can close this and do the same for the other PR :)

**Comment by JoelLarson** [comment]
@Torxed I've regenerated the changes with the latest. There were a few changes that were made in each file. #1341 will require more than a rebase.

**Comment by JoelLarson** [comment]
Github actions could be used for adding a check to make sure they are always current.

**Comment by Torxed** [comment]
Thanks! Yea there's always room for improvement, feel free to submit a PR for that if you wish :) Otherwise I'll have to add it to my pile sadly.

**Comment by JoelLarson** [comment]
I can work on that when I find some time.

**Pull request merged**
