### PR TITLE
Add `_get_kernel_params()`

### PR DESCRIPTION
**Pull request by codefiles**
The kernel parameters used in `_add_systemd_bootloader()` and `_add_efistub_bootloader()` should be identical.

### CODE REVIEW

**Review by Torxed — APPROVED** [review]

**Comment by svartkanin** [comment]
Looking at the efistub and systemd implementations they do have some differences 
* zram 
* subvols
* hsm

are we saying that those were originally missing from the efistub setup?

**Comment by codefiles** [comment]
Yes, they **should** be identical and are not since those are missing. This is intended to fix that and keep the code from being duplicated.

**Comment by svartkanin** [comment]
Gotcha, I see that grub also doesn't have them, are they missing their as well?

**Comment by codefiles** [comment]
I plan to investigate application of this function to the other boot loaders. It may require additional changes to work with GRUB since by default `grub-mkconfig` determines the root filesystem.

**Pull request merged**
